### ISSUE TITLE
base_class.supported_extensions[i].toLowerCase is not a function

### ISSUE THREAD

**Issue by mercurio** [jagenjo/litegraph.js#100]
When I load litegraph.min.js I get this error:

Uncaught TypeError: base_class.supported_extensions[i].toLowerCase is not a function

Looking at the unminified litegraph.js, the problem is in the loop at line 194. i assumes, first, the indices into the array, then additional properties like 'isEnumerable', which triggers the error. I patched it by adding

`if (typeof i !== 'number') continue`

at the start of the loop (after line 194).

**Comment by jagenjo** [comment]
but that only could happend if one node added a supported extension that is a number, which is weird because they are suppposed to be stuff like ".png" etc

**Comment by mercurio** [comment]
This is happening when loading the library, before making any calls into it. base_class.supported_extensions['isEnumerable'] is not a string and does not have a toLowerCase() function.

This is on a current version of Chrome (Windows). Maybe you're seeing different behavior in another browser.

**Comment by jagenjo** [comment]
to me it looks like one of your libraries is modifiying one system class.
I uploaded a version that controls that strange case but others could appear related to that.
I will explore further

**Comment by mercurio** [comment]
You're right, one of my other libraries is adding additional functionality to arrays that's causing this (I suspect it's Ember). Thanks for handling this!
