### ISSUE TITLE
Can I add an undo function?

### ISSUE THREAD

**Issue by sheenli** [jagenjo/litegraph.js#101]

**Comment by jagenjo** [comment]
I can add it to the LiteGraphEditor but not to the LGraphCanvas

**Comment by sheenli** [comment]
it is good

**Comment by sheenli** [comment]
LiteGraphEditor and LGraphCanvas Are they separate ？
Only one file litegraph.js？

**Comment by jagenjo** [comment]
LiteGraphEditor is the full editor you can see here (with buttons and so).
LGraphCanvas is just the canvas, without buttons.
They are in separate files because most people want to implement their own interface for the LGraphCanvas.

**Comment by sheenli** [comment]
me too TAT

**Comment by sheenli** [comment]
I want to embed in electron

**Comment by sheenli** [comment]
![image](https://user-images.githubusercontent.com/13329486/74952430-352a7500-543b-11ea-8784-2f989b27e350.png)
I only use litegraph.js error，but use npm install litegraph.js is OK.

**Comment by jagenjo** [comment]
some features require to install extra libraries like:

https://github.com/jagenjo/Canvas2DtoWebGL/blob/master/src/gl-matrix-min.js
https://github.com/jagenjo/Canvas2DtoWebGL/blob/master/src/litegl.js
https://github.com/jagenjo/Canvas2DtoWebGL/blob/master/src/Canvas2DtoWebGL.js

**Comment by sheenli** [comment]
OK

**Comment by sheenli** [comment]
How to close if I don't use gl？

**Comment by jagenjo** [comment]
no idea

**Comment by sheenli** [comment]
hah , I first try to add dependencies, thank you very much

**Comment by sheenli** [comment]
![image](https://user-images.githubusercontent.com/13329486/74955139-28a81b80-543f-11ea-95ad-ee3b923a6d37.png)

i add require("gl-matrix-min")
require("litegl")
require("Canvas2DtoWebGL")

**Comment by jagenjo** [comment]
I never use npm so I dont know how to solve it. I use it only in the browser.

**Comment by sheenli** [comment]
i use nmp i -D litegraph.js no error
