### ISSUE TITLE
Option to style the background, grid and border of the selected nodes ?

### ISSUE THREAD

**Issue by egeres** [jagenjo/litegraph.js#104]
So far I couldn't find variables to style the background color of the grid as well as the grid lines and the color of the outline of a node that is drawn when they are selected. I've only searched for this on the global.LiteGraph object that configures other theme parameters and I couldn't find them. Is it implemented in the code ?

**Comment by Wayne5202** [comment]
litegraph.js about line 4338 is using a base64 image for the background.  
<code>
  function LGraphCanvas(canvas, graph, options) {
        options = options || {};
        //if(graph === undefined)
        //	throw ("No graph assigned");
        this.background_image =
            "data:image/png;base64,..........................................."
</code>
You can create your own background by using a img to base64 converter or by creating a function:

Borrowed code from Max Smirnov's Moi Node Editor:
http://moi.maxsm.net/

<code>
Editor.prototype.generateBackground = function()
{
	var bgvcanvas = document.createElement("canvas");
//	var bgsize = 100 * ( this.uiRatio || 1);
	var bgsize = 100;
	var bgstep = bgsize / 10;
	bgvcanvas.height = bgvcanvas.width  = bgsize;
	var bgvctx = bgvcanvas.getContext("2d");
	// bgvctx.fillStyle = scheme.getColor('editor_background');
	bgvctx.fillStyle = "rgb(225,223,217)";
	bgvctx.rect(0, 0, bgsize, bgsize); bgvctx.fill();
	// bgvctx.strokeStyle = scheme.getColor('editor_grid');
	bgvctx.strokeStyle = "rgb(208,206,201)"
	for ( var i=0; i<10; i++ )
	{
		bgvctx.beginPath();		bgvctx.moveTo(0.5, i*bgstep+0.5);	bgvctx.lineTo(bgsize+0.5, i*bgstep+0.5);	bgvctx.stroke();
		bgvctx.beginPath();		bgvctx.moveTo(i*bgstep+0.5,0.5);	bgvctx.lineTo(i*bgstep+0.5,bgsize+0.5);		bgvctx.stroke();
	}
//	bgvctx.beginPath();		bgvctx.moveTo(1.5, 1.5);	bgvctx.lineTo(bgsize+0.5, 1.5);		bgvctx.stroke();
//	bgvctx.beginPath();		bgvctx.moveTo(1.5, 1.5);	bgvctx.lineTo(1.5, bgsize+0.5);		bgvctx.stroke();
	var bgr = bgvcanvas.toDataURL("image/png",0);
	return bgr
}
</code>

**Comment by egeres** [comment]
Thank you, it works as expected!

I've also found that the outline of a selected node can be edited in the method `LGraphCanvas.prototype.drawNodeShape` , more specifically, inside the block controlled by the variable `selected`

**Comment by jagenjo** [comment]
you do not need to use the base64 encoding, just pass the url of an image with the grid and it will use it.
