### ISSUE TITLE
As a litegraph user, I'd like to have the ability to de-register nodes

### ISSUE THREAD

**Issue by sashamitrovich** [jagenjo/litegraph.js#105]

**Comment by jagenjo** [comment]
Instead of including the build/litegraph.js that contains all the nodes, include src/litegraph.js (this doesnt contain any node) and the individual files in nodes/ that contain the nodes you want, they are in files by category.

**Comment by sashamitrovich** [comment]
We're looking to remove nodes to the graph dynamically. We add nodes now dynamically so we need the opposite thing. This is our project: https://github.com/marklogic-community/pipes

 How would that work?

**Comment by jagenjo** [comment]
Then go to ```LiteGraph.registered_node_types``` and remove them from there:
```delete LiteGraph.registered_node_types["math/trigonometry"];```
I will consider adding a unregisterNodeType in the next version.

**Comment by sashamitrovich** [comment]
Will try and let you know, thanks!

**Comment by danielholgate** [comment]
Hi @jagenjo With regards to this, I've tried accessing **LiteGraph.registered_node_types** directly from our code (ie starting with console.log(LiteGraph.registered_node_types) but for some reason this always returns {} even though i know we have a number of nodes registered

**Comment by jagenjo** [comment]
Thats weird, are you sure you are not calling it before the nodes are registered? 
If you open the dev console and type that it shows empty?

**Comment by danielholgate** [comment]
Yes it's odd.. this is not directly after node registration, I have already registered the nodes long before this and put them on a graph etc. I'll keep playing around with it

**Comment by fronald** [comment]
Just redefine it.

```javascript
// Clear all
litegraph.LiteGraph.registered_node_types = [];

// Add your nodes
litegraph.LiteGraph.registerNodeType("My/Node", MyNode);

const graph = new litegraph.LGraph();
...
```
