### ISSUE TITLE
"First project" throws error and doesn't render anything

### ISSUE THREAD

**Issue by PatrickSachs** [jagenjo/litegraph.js#109]
Hello there!

Litegraph looks like a really impressive project. I am currently in the process of migrating a project away from Rete.JS due to its lack of documentation and proper TypeScript support.

However, I'm running into a problem with your demo project in the README. It appears, that the `ConstantNumber` class does not have a `setValue` function, which is used in the example:

```
Edit.vue?a54f:66 TypeError: node_const.setValue is not a function
```

If I remove the line in question no error occurs, but nothing is rendered in my canvas. I expected to see a functioning editor like on your demo page with a constant number connected to a watch.

Furthermore I have some general questions about the project. If you want me to create a separate issue for each quesiton please tell me and I'll do so:

- The workflow for our users looks like this: They have an editor and create a graph in it. The graph defines the control flow of an application (with conditionals, variables, etc...) which is later serialized to (preferably) a JSON string. 
This serialized string would be loaded during the runtime of the application and executed without showing an editor or a LiteGraph related GUI. 
Bonus points if it is aditionally easily possible to show a debugger to the developer.
Does Litegraph.js support these features? Especially the decoupled GUI from execution and (possibly asynchronous) conditional execution paths are important.

- How good is the TypeScript support? Since this project is written in JavaScript and not TypeScript the definitions are probably manually created. Can we rely on them always being accurate? Since I'd rather use a project without TypeScript definitions than one with broken ones.

- I'm a bit concered about the maintainability of this project. The complex tooling for compilation instead of webpack and use of JavaScript over TypeScript especially stands out. Is it difficult to set up a development environment if we would have to fork the project to make adjustments to the core? Is the code written in a maintainable fashion so that it's easy to understand what's going on without extensive experience in the project?

Thanks for your time and effort put into this project. It always amazes me how many great open source projects are out there! :)

Have a great day,
Patrick

**Comment by TunaYagci** [comment]
hi @jagenjo can we have an update on this issue? Are you accepting any PRs?

**Comment by jagenjo** [comment]
Hi
Sorry, totally missed this ticket.
I already fixed it and uploaded it to github.

About the features commented, all of them are supported (you can even run the graphs in nodejs).

About the debugger, you can code anything inside your own nodes if you need to add debugging features. The editor come with some basic features (like highlighting the connections when an event is triggered through it) but they are not very powerful. But feel free to add what you need on top.

About typescript, Im not handling the typescript support as it was done by somebody else, so I cannot give you much info about.
