### ISSUE TITLE
Node links are not cleared after they are invalidated

### ISSUE THREAD

**Issue by crener** [jagenjo/litegraph.js#11]
If you go to the demo application and make a few nodes and link them together and serialize the graph (`graph.serialize()`), look at the amount of links that were made. Then go and change and change a few of the links around but keep the amount of visible links the same, when you go and serialize the graph again the number of links from the serialized objecct has increased but the actual links on the graph is still the same.

https://imgur.com/DG6i027

Should a link not be discarded when it is invalidated?

**Comment by crener** [comment]
I suppose you could cross reference the links and each nodes link ids and then eliminate the links tat way...

**Comment by jagenjo** [comment]
you were right, there was a line missing when disconnecting a link to remove it from the links pool of the graph. I just added it. I dont have time to test it properly but it looks like it works.

let me know if you find anything else.
