### ISSUE TITLE
SubGraph serialize error

### ISSUE THREAD

**Issue by goodgecko** [jagenjo/litegraph.js#117]
Hey Jagenjo, I noticed when I tried saving a scene with a subgraph on stage, it crashed in Subgraph.prototype.serialize() with LGraphNode undefined. I'm building the project in Typescript so it might be doing something funny in the js bundling.

In litegraph.js, adding LiteGraph before LGraphNode resolved the issue:
var data = LiteGraph.LGraphNode.prototype.serialize.call(this);

Hope this helps, its a great tool I've had a lot of fun playing with.

**Comment by jagenjo** [comment]
Yes, there is an issue open about subgraphs crashing in some cases:
https://github.com/jagenjo/litegraph.js/issues/93

I have to check it, I hope I will have some time this week to do it.

Cheers

**Comment by jagenjo** [comment]
I just added your fix.
