### ISSUE TITLE
Modularize project for easier development

### ISSUE THREAD

**Issue by kriffe** [jagenjo/litegraph.js#12]
Have started an experimental branch for a modular structured project. https://github.com/kriffe/litegraph.js/tree/1712125_ES6_experiment

- Separate LGraph, LGraphCanvas, LGraphNode into separate files
Untangle dependencies

- Add all calls to container
LITEGRAPH.LGraphNode... etc

- Possibility to import project as ES6 Module (fully supported in 2018)
Limit API from outside (what is really needed?)
Add webpack for bundling of projcet
Include as: import LITEGRAPH from 'litegraph.js'

This will need to be a major release and break backward compatibility. 
@jagenjo How will this impact https://github.com/jagenjo/webglstudio.js ?

**Comment by kriffe** [comment]
Default node items in progress

**Comment by kriffe** [comment]
@jagenjo : What is the reason for having multiple one LGraph and multiple canvases  (graph.list_of_graphcanvas)? Is this used somewhere?

**Comment by kriffe** [comment]
Perhaps a bit early. Leaving branch alive for the future (unstable). Wait on full support and somewhat more mature philosophy of how to apply.

https://www.contentful.com/blog/2017/04/04/es6-modules-support-lands-in-browsers-is-it-time-to-rethink-bundling/

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import

**Comment by jagenjo** [comment]
You can have several canvas and several graphs, this is used in my editor so you can have a graph for behaviour and a graph for rendering and edit them independly. Also you can have a secondary canvas as a zoom out of the current canvas.

About moving everything to ES6, Im not very fond, there are still mobile browsers and consoles that does not support it fully.

**Comment by kriffe** [comment]
This seems to be resolved with the last refactoring. Closing
