### ISSUE TITLE
Undefined error on "number" widget mousedown event

### ISSUE THREAD

**Issue by atpw25** [jagenjo/litegraph.js#120]
I am getting the following error when using the "number" widget (e.g. basic/const).

<img width="517" alt="Screenshot 2020-04-21 at 10 10 57" src="https://user-images.githubusercontent.com/5221062/79848643-43542d80-83b9-11ea-8e8c-52009d27e17e.png">

The error seems to be coming from line 8416 below. Changing the code at line 8412 to `var values = w.options.values || {};` fixed the problem for me.

https://github.com/jagenjo/litegraph.js/blob/6b95b4742155205bbb47fbc17b225b07bd63b056/src/litegraph.js#L8411-L8418

Version: 0.7.5

**Comment by jagenjo** [comment]
you are right, I was using the same part of the code for several cases and number shouldnt be in the same case.
I added a fix although it is different from yours as mine checks that it is in the right case.
