### ISSUE TITLE
Cannot read property 'CanvasRenderingContext2D' of undefined

### ISSUE THREAD

**Issue by atpw25** [jagenjo/litegraph.js#121]
This error (and #120) occurs when using litegraph under Angular 9. 

<img width="514" alt="Screenshot 2020-04-21 at 10 45 23" src="https://user-images.githubusercontent.com/5221062/79852502-a5636180-83be-11ea-9029-cbfe263b31c8.png">

Changing line 10116 from `if (this.CanvasRenderingContext2D) {` to `if (window.CanvasRenderingContext2D) {` fixed it for me.

https://github.com/jagenjo/litegraph.js/blob/6b95b4742155205bbb47fbc17b225b07bd63b056/src/litegraph.js#L10116-L10119

Version: 0.7.5

**Comment by jagenjo** [comment]
Fixed
