### ISSUE TITLE
Cannot read property 'constructor' of undefined

### ISSUE THREAD

**Issue by ding-hub** [jagenjo/litegraph.js#125]
Testing this out for Vue so using it as an import.
`import { LiteGraph } from "litegraph.js"`
I get this error when clicking single value widget.

> litegraph.js?6e14:8403 Uncaught TypeError: Cannot read property 'constructor' of undefined
>at LGraphCanvas.processNodeWidgets (litegraph.js?6e14:8403)
>at LGraphCanvas.processMouseDown (litegraph.js?6e14:5149)

had to add this to line 8402 to fix on a const number or similar single item widget
```
if (values)
    var values_list = values.constructor === Array ? values : Object.keys(values);
```

**Comment by jagenjo** [comment]
this error was corrected one week ago in the github version, maybe if you are using the npm is not updated yet

**Comment by ding-hub** [comment]
yup, using the npm version
