### ISSUE TITLE
npm 0.7.6 update error

### ISSUE THREAD

**Issue by ding-hub** [jagenjo/litegraph.js#126]
updating to npm version 0.7.6 I get the following error when creating any node.

> litegraph.js?6e14:7465 Uncaught TypeError: ctx.roundRect is not a function
>     at LGraphCanvas.drawNodeShape (litegraph.js?6e14:7465)
>     at LGraphCanvas.drawNode (litegraph.js?6e14:7066)
>     at LGraphCanvas.drawFrontCanvas (litegraph.js?6e14:6645)
>     at LGraphCanvas.draw (litegraph.js?6e14:6556)
>     at LGraphCanvas.renderFrame (litegraph.js?6e14:4999)

downgraded to 0.7.5 with the processNodeWidgets fix and its working again so something going on with 0.7.6

**Comment by jagenjo** [comment]
oh, try now

**Comment by ding-hub** [comment]
yup, that works. thanks!
