### ISSUE TITLE
onConnectInput invalid parameter ?

### ISSUE THREAD

**Issue by altarfinch** [jagenjo/litegraph.js#128]
When connecting two nodes, onConnectInput is triggered on the target node.
However, outputSlot parameter is initialized after, so we can't really use it to determine if we should allow connection or not.

**Comment by jagenjo** [comment]
I added the node and the slot as parameters:
`            if ( target_node.onConnectInput(target_slot, output.type, output, **this, slot**) === false ) {`

That should be enough.
