### ISSUE TITLE
widget draw method wrong parameter + custom height ?

### ISSUE THREAD

**Issue by altarfinch** [jagenjo/litegraph.js#132]
I tried to create a custom widget using IWidget, but something isn't clear:
In the definition file, we have this signature

```
draw?(
    ctx: CanvasRenderingContext2D,
    node: LGraphNode,
    width: number,
    posY: number,
    height: number
): void;
```

The definition seems right to me, but in the code, the width parameter is in fact a widget.

In the JS:
`w.draw(ctx, node, w, y, H);`
should be
`w.draw(ctx, node, width, y, H);`

Also, it would be nice to allow for custom height by allowing draw to return a number, this way we could mix for example texture or curve widgets with the default ones without having to manipulate size or having to play with LGraphNode's onDrawForeground.

**Comment by jagenjo** [comment]
whats Iwidget?

**Comment by altarfinch** [comment]
IWidget is the widget interface definition that wraps node widgets (number, slider, combo, text, toggle, button):

```
export interface IWidget<TValue = any, TOptions = any> {
    name: string | null;
    value: TValue;
    options?: TOptions;
    type?: widgetTypes;
    y?: number;
    property?: string;
    last_y?: number;
    clicked?: boolean;
    marker?: boolean;
    callback?: WidgetCallback<this>;
    /** Called by `LGraphCanvas.drawNodeWidgets` */
    draw?(
        ctx: CanvasRenderingContext2D,
        node: LGraphNode,
        width: number,
        posY: number,
        height: number
    ): void;
    /**
     * Called by `LGraphCanvas.processNodeWidgets`
     * https://github.com/jagenjo/litegraph.js/issues/76
     */
    mouse?(
        ctx: undefined,
        event: MouseEvent,
        pos: Vector2,
        node: LGraphNode
    ): void;
}
```

In the function **LGraphCanvas.prototype.drawNodeWidgets**, you do:

`Line(8231) var width = node.size[0];`
`Line(8245) var w = widgets[i];`

And I think the two ar mixed up:

`Line(8415) w.draw(ctx, node, w, y, H);`

The w parameter you pass should be width

**Comment by jagenjo** [comment]
so they are mixed in the TS description or in my library?

**Comment by altarfinch** [comment]
They are right in the TS definition and mixed in your library.

I think it's a typo, you want to pass **width**, as it's useful to know the width to draw a widget that expand when resizing the node, and as we already have **w** in the widget's draw function override  as it's equal to **this**.

You should just replace this line:

`w.draw(ctx, node, w, y, H);`

by:

`w.draw(ctx, node, width, y, H);`

Additionally, it would be nice to allow **draw** to return an optionnal custom height **number | undefined** and do something like :

insert [Line(8245)](https://github.com/jagenjo/litegraph.js/blob/master/src/litegraph.js#L8245):
`var h = H;`

replace [Line(8415)](https://github.com/jagenjo/litegraph.js/blob/master/src/litegraph.js#L8415) by:
`h = w.draw(ctx, node, width, y, H) | H;`

replace [Line(8419)](https://github.com/jagenjo/litegraph.js/blob/master/src/litegraph.js#L8419) by: `posY += h + 4;`

This way one could stack easily multiple custom widget with custom height.

**Comment by jagenjo** [comment]
makes sense, I just corrected it. Never used that function as it was meant for someone who wanted to create their own widgets.

It will be uploaded with the next version, thanks

**Comment by altarfinch** [comment]
Thanks for the fix.

Additionally, if one wants to align its widget with the others, he will need to add [a margin of 15](https://github.com/jagenjo/litegraph.js/blob/master/src/litegraph.js#L8242).

Following the style of others global variable such as :

```
WIDGET_BGCOLOR: "#222",
WIDGET_OUTLINE_COLOR: "#666",
WIDGET_TEXT_COLOR: "#DDD",
WIDGET_SECONDARY_TEXT_COLOR: "#999",
```

You could add:

`WIDGET_MARGIN: 15,`

But maybe I'm too greedy ;)
