### ISSUE TITLE
unRegister All

### ISSUE THREAD

**Issue by iyobo** [jagenjo/litegraph.js#136]
A starting project starts with a whole lot of nodetypes already registered.
How can all these starting nodetypes be unregistered en masse?

**Comment by altarfinch** [comment]
What I do:
`LiteGraph.registered_node_types = {};`

**Comment by jagenjo** [comment]
That should work but I never tested it.

**Comment by iyobo** [comment]
This works and resolves this issue. Thanks @altarfinch !
