### ISSUE TITLE
Problems with using in react

### ISSUE THREAD

**Issue by ShaubertIlya** [jagenjo/litegraph.js#14]
Hello and good day. Sorry if the question is silly but can you give an advice about the mistake i've got?
 I've installed library throw command "npm install litegraph.js" and now i see it's folder inside of my modules folder. I  imported it like this " import LGraph from 'litegraph.js' ". React shows me an error 

ReferenceError: LGraph is not defined

My code:

import React, { Component } from 'react';
import {Layer, Rect, Stage, Group} from 'react-konva';
import LiteGraph from 'litegraph.js'
import LGraph from 'litegraph.js'

class MyRect extends Component
{
    render()
    {
        var graph = new LGraph();

        return(
            <canvas id='mycanvas' width={1024} height={720}></canvas>
        );
    }
}

export default MyRect;

**Comment by jagenjo** [comment]
LiteGraph is not supported by node yet, so it doesnt work in systems like react that rely in modules

**Comment by vivekascoder** [comment]
Is it still the case?
