### ISSUE TITLE
Resizing fixed ratio widget regression

### ISSUE THREAD

**Issue by altarfinch** [jagenjo/litegraph.js#143]
I experience a regression since this [commit] https://github.com/jagenjo/litegraph.js/commit/e6c5474155a83967ade46fe6e588951978707516#r39833636)
The way it used to work allowed to have a widget with a growing size and a fixed ratio (e.g. a 16/9 stream preview which would fill max width and the height according to the ratio).
Now the resizing crops it to the minimal size.

**Comment by jagenjo** [comment]
can you elaborate more? 
this change shouldn't affect AFAIK

**Comment by altarfinch** [comment]
Behaviour (from left to right):
1. resized to minimum
2. default size
3. resized to the right
4. resized to diagonal left+right

Previous behaviour:
![Previous behaviour](https://user-images.githubusercontent.com/25177039/84489341-d9ae1c80-aca1-11ea-8068-6b1073ee0528.PNG)

New behaviour:
![New behaviour](https://user-images.githubusercontent.com/25177039/84489352-dfa3fd80-aca1-11ea-87aa-152c8248d9ba.PNG)

We can see in the new version the new minimum size behaviour (1.).
However when you resize to the right (3.), it looks like only the minimum height of the widget is taken into account and not the actual height. I think it's because you removed the call to `widget.computeSize`.

Here is the `computeSize` override function used for the screenshots:

```
public computeSize(width: number): [number, number] {
	const widgetWidth = Math.max(0, width - DiagramWidget.WIDGET_MARGIN * 2);
	const widgetHeight = widgetWidth / (this.resolution[0] / this.resolution[1]);
	return [widgetWidth, widgetHeight];
}
```

**Comment by jagenjo** [comment]
I still do not understand. Your node has a non-standard widget that has some specific height?
did you implement the widget.computeSize method?

**Comment by altarfinch** [comment]
My node has a fixed ratio: `height = width * ratio`
I implemented `widget.computeSize`. Before the update, it was taken into account properly.
Do you want me to fix it ?

**Comment by jagenjo** [comment]
yes, please, because I can't really understand your use case. sorry
