### ISSUE TITLE
Tree widget implementation is needed

### ISSUE THREAD

**Issue by proxy-m** [jagenjo/litegraph.js#148]
Something visually like jsTree: https://old.jstree.com/ and https://www.jstree.com/demo/ .

Tree as input widget: on tree nodes selections (key - node path, value - node associated data and/or action).

Tree as output: redner json and other structures as a tree.

Tree nodes (path, value data and action) can be editable with litegraph.

P.S.: It is not essential to use jsTree code, but it is possible.

**Comment by jagenjo** [comment]
Coding a tree widget inside the node is out of the scope now, but feel free to follow the guides to create your own widgets.

https://github.com/jagenjo/litegraph.js/tree/master/guides
