### ISSUE TITLE
onExecute returning promise

### ISSUE THREAD

**Issue by coderofsalvation** [jagenjo/litegraph.js#15]
Hi, im currently playing with litegraph (to embed in a project).
I need async, and since onExecute() is synchronous i need to hack some async magic in there.

Looking at the source, it seems that i can simply monkeypatch the runStep function:

https://github.com/jagenjo/litegraph.js/blob/2e16b6560a50a741e733b2e48ba22816a789a9c0/src/litegraph.js#L469

> It seems it just loops through the nodes synchronously, so i can replace that with an async loop.

Can you let me know if my logic makes sense?

**Comment by jagenjo** [comment]
Hi,

Technically yes, thats the function that iterates through every node calling the onExecute on them.
But what I do not understand is why you want something that is not asyncronous to be asynchronous when onExecute methods are not depending on external stuff.

I mean, you can wrap it if you want, but it is still a sync code called from an async wrapper.

The only use case I can imagine is if one node relies on some async actions, but in that case it will be harder that wrapping onExecute, you will need to call onExecute after the async onExecute finishes, and that would take some time to code. I guess you can create a runStepAsync that handles promises in some sort of onExecuteAsync, but then you will have to handle which nodes are sync and which ones arent.

Tell me more about your use-case

**Comment by coderofsalvation** [comment]
that's exactly what I'm going for.

**Comment by jagenjo** [comment]
Well, I though about it too some time ago, and my approach was more focused in events, similar to how UDK4 Blueprints work, where a node can dispatch an event, and you can wire events between boxes.

The current approach is more for signal processing (take one input, process it, generate output).

LiteGraph currently supports events, it is not well documented, but the feature is there. The idea is that you can declare event inputs/outputs and connect them, and from a node you can dispatch them using the method trigger. This will execute independently of runStep.

Let me know your advances.
