### ISSUE TITLE
Possible to make "object nodes" and get reference?

### ISSUE THREAD

**Issue by CosmicSnow** [jagenjo/litegraph.js#152]
Ok, I have an educational project where I need to create a bot using a nonSQL DB (firebase, mongodb etc).
I'll try my best to explain what I'm trying to do:

So, I have a chat bot, where it's structure is object oriented, where the object names matters, and each object is composed by,
A Text and it's next steps.
All object steps are structured the same way.

example of S Objects (S is just a prefix for the object name):
```javascript
s0: {
      text: "Hello and welcome to botchat."
      nextStep: {
                      "1": { description: "show Website link", target: "s1"}
                      "2": { description: "end chat", target: ""}
                      }
}
```
```javascript
s1: {
      text: "some website here."
      nextStep: {}
}
```

I have a backend to treat it, so don't really mind so much how it works, 
So, what I am trying to do is create a Node where it acts like these S Objects.

Is it possible make the bot flow using litegraph? is Yes, how hard will it be?

**Comment by jagenjo** [comment]
It shouldnt be hard, you must programme your own Dialog node.
There are Event slots that trigger when an action is performed, so using them may work.
BUt I recommend you take a deep look in how the system works as this situation wasnt in mind when the system was created and you will need to tweak some parts.

**Comment by CosmicSnow** [comment]
thanks @jagenjo I'll try it next weekend! I'll study the documentation first.
