### ISSUE TITLE
Background and SubGraph error

### ISSUE THREAD

**Issue by Hermades** [jagenjo/litegraph.js#159]
Hello @jagenjo. I wanted to show you that I've a few bugs on my project with this library. One of them is the background, which ain't drawn (the grey background you see is a div element) and the another one is referred to Subgraphs. The Input node works perfectly, but when I want to connect a subgraph's Output to another's Input it returns null.

![Screenshot_2020-07-15_19-26-19](https://user-images.githubusercontent.com/63685134/87587413-95af9c80-c6d1-11ea-976f-41a2f7260cc6.png)

Thanks for your time, and I hope you can help me <3
Cheers /Sarah.

**Comment by jagenjo** [comment]
The background is strange. Do you have an online copy where I can check it?

About the output, did you specity the output type of the subgraph in the output node?

**Comment by Hermades** [comment]
Hi. Yep, the entire code is in this repository: https://github.com/GorlotEngine/Engine/. The Material editor is this file: https://github.com/GorlotEngine/Engine/blob/master/Editor/src/editor/ui/tab/MaterialEditor.js, and the Subgraph nodes are here: https://github.com/GorlotEngine/Engine/blob/master/Editor/src/core/nodes/base/Logic.js
