### ISSUE TITLE
Can't start the project

### ISSUE THREAD

**Issue by SaraGhlm** [jagenjo/litegraph.js#166]
Hello,

I am sorry if I'm asking a very basic question here. But I'm very new to node and I'm facing problems running this project. I am following the commands in the [Demo](https://github.com/jagenjo/litegraph.js#demo) but when I check my localhost the only thing that appears is "Cannot GET /". 
I am running it on Windows 10. Also, I checked it on Ubuntu but the same happened. 

In the Chrome dev tools console I'm getting this error "Refused to load the image 'http://localhost:8000/favicon.ico' because it violates the following Content Security Policy directive: "default-src 'none'". Note that 'img-src' was not explicitly set, so 'default-src' is used as a fallback."

Thank you in advance for your help.
![image](https://user-images.githubusercontent.com/13000341/90441896-f8ac9e80-e096-11ea-97dd-8c5fe94dc0bc.png)

**Comment by jagenjo** [comment]
Hi Sara, as Sarah said, the NPM version is only for people who want to do fanzy stuff. The simplest way is to download the repo (using the CLONE button), and copy the library files into your website. There is also the EDITOR folder that contains an aplication using the library but you don't need to use it if you dont want.

Just include build/litegraph.js and css/litegraph.css in your HTML and you can start using it.
