### ISSUE TITLE
Demo is a 404 page

### ISSUE THREAD

**Issue by fadookie** [jagenjo/litegraph.js#168]
1. https://tamats.com/projects/litegraph/demo is a 404
2. Following instruction in README to run demo locally also results in a 404 from node

It appears that here in `utils/server.js`: 
```javascript
app.use('/demo', express.static('demo'))
app.use('/', express.static('demo'))
```

I think you are telling express to serve files from `/demo` folder in repo root, but no such folder seems to exist on a clean clone. If there is a script that needs to be run to generate this, I couldn't find any documentation on where it is.

**Comment by SarahThePanda** [comment]
You can simply go to: https://tamats.com/projects/litegraph/editor/, or if you want to open it in a local way "[repo root]/editor/index.html"

**Comment by fadookie** [comment]
Thanks! That's helpful, but I'll leave this issue open since the docs are still pointing to broken links.

**Comment by jagenjo** [comment]
yes, I renamed the demo to editor, I will fix the link.
