### ISSUE TITLE
Questions from new user, unable to resize node

### ISSUE THREAD

**Issue by fadookie** [jagenjo/litegraph.js#170]
Hello,
I have been trying to build a prototype of an animation blending engine using litegraph.js.

Overall it's been going pretty well but I have run into a few issues. It's likely these are problems on my side but I don't see any other support channel so I am opening an issue for this one I haven't been able to solve on my own. If you want I can keep posting these questions here so I don't clog up the issue tracker.

## Incorrect node size, unable to resize
After attaching a couple of widgets to the [AnimationClip](https://github.com/fadookie/blendtree-prototype/blob/7dcd05d8dd2f9e7b3e8e562b9c5094e1fbbb2c2a/src/components/AnimationClip.js), the node does not auto-resize correctly. I see there's code in there that looks like it should be doing this so I don't know what's going wrong since it works fine on the Blend2 node.

I have tried setting the size manually in the constructor like I've seen some of the other components do, but this seems to have no visible effect even when I try to make it square or use very large values.

<img width="445" alt="Screen Shot 2020-09-01 at 10 07 14 AM" src="https://user-images.githubusercontent.com/110764/91884529-09cee100-ec3b-11ea-9f9a-74290dc5ffeb.png">

**Comment by fadookie** [comment]
# Stale widget data
I have also observed on occasion after deserializing the graph, widgets may display default values instead of the loaded value of the property.

<img width="493" alt="Screen Shot 2020-09-01 at 10 35 30 AM" src="https://user-images.githubusercontent.com/110764/91887057-20773700-ec3f-11ea-9b57-2650cd8dbc4f.png">

I don't know if I'm doing something wrong or if this is a bug.

**Comment by jagenjo** [comment]
for the size, set the size in the constructor after creating all the inputs and widgets.

for the value, how do you define the widget?

**Comment by fadookie** [comment]
Thanks for the response. I linked to the code on the original post.

For size, I tried doing that already but it seemed to have no visible effect, even when set to very large values.

In constructor for AnimationClip, adding this:

```javascript
this.setSize = [2000, 2000];
```

has no effect.


Doing it this way:
```javascript
this.setSize(2000, 2000);
```

Changes the background color for some reason and hides the widgets, but the node remains the same size:
<img width="190" alt="Screen Shot 2020-09-01 at 10 43 52 AM" src="https://user-images.githubusercontent.com/110764/91887758-0b4ed800-ec40-11ea-9b20-694cb5ec5e25.png">

**Comment by fadookie** [comment]
Oh I think I see why the red thing is happening at least, it says `TypeError: this.setSize is not a function` - which is weird, I thought it should have been added to the prototype when I register my component?

**Comment by jagenjo** [comment]
this.size = [200,200]

**Comment by fadookie** [comment]
I tried that already like I said, it looks the same no matter what value I set `this.size` to, here's `this.size = [200, 200]` which looks the same as `this.size = [2000, 2000]`:
<img width="221" alt="Screen Shot 2020-09-01 at 10 56 12 AM" src="https://user-images.githubusercontent.com/110764/91888937-e491a100-ec41-11ea-834c-2cac0bc5495e.png">

**Comment by jagenjo** [comment]
paste the constructor code

**Comment by fadookie** [comment]
https://github.com/fadookie/blendtree-prototype/blob/6738fd8aecbd82f420390777603621d1ac6c4fc2/src/components/AnimationClip.js#L7-L21

**Comment by jagenjo** [comment]
![image](https://user-images.githubusercontent.com/393515/91889591-52fc5080-ec8e-11ea-853d-73b9bb3d3063.png)
pasting yor code.

do you remember to register it?
`LiteGraph.registerNodeType`

**Comment by fadookie** [comment]
Yes, the node shows up in the node context menu. It's strange, maybe one of the other methods on the prototype is interfering with it somehow? If you download my whole repo there you should see the issue. I don't want to take up too much of your time though, since this is purely an aesthetic issue I can live with it. Thanks.

**Comment by jagenjo** [comment]
if you have it online somewhere I may enter to see what happens, otherwise I cannot debug it

**Comment by fadookie** [comment]
Okay, I published it here: https://www.eliotlash.com/blendtree-prototype/

**Comment by jagenjo** [comment]
you are loading a JSON that contains the size of every node, that size overwrites the size defined by the constructor. if you create a new node it will use the one defined in the ctor.

**Comment by fadookie** [comment]
Uh, I got this json from the serialize function - maybe it should be filtered out of the serialization operation? Otherwise this is gonna keep happening every time I save.

**Comment by jagenjo** [comment]
thats the purporse of serializing, storing the current state of any node. just create the nodes with the right size and it will stored with the right size. you are reloading a json that you created when the size was not well defined, stop using that json
