### ISSUE TITLE
How to save/load a local file containing the graph

### ISSUE THREAD

**Issue by RiccardoRossi** [jagenjo/litegraph.js#171]
Dear @jagenjo we would like to make a simplified version of your demo, which allows us loading a local file and downloading the workspace to a json file (which can itself be loaded a second time)

so far we (@roigcarlo who did the work) achieved this by modifying the 'litegraph.js' by adding the following function

~~~js
    LGraph.prototype.loadFile = function(url) {
        var that = this;

        const reader = new FileReader();
		reader.addEventListener('load', (event) => {
            var data = JSON.parse(event.target.result);
            that.configure(data);
        });
        
        reader.readAsText(url);
    };
~~~

of course such a solution is suboptimal since it implies editing your lib instead of using as it is.

Do you have any alternative solution?

**Comment by jagenjo** [comment]
I think is a clean solution, I will just used fetch though:

```js
	fetch( url ).then(function(response) {
		return response.json();
	}).then(function(data){
		that.configure( data );
	});
```

**Comment by jagenjo** [comment]
oh, you want to load from file, not from url, then your solution is perfect.

**Comment by jagenjo** [comment]
I just uploaded a version that supports to pass a file to graph.load

**Comment by RiccardoRossi** [comment]
wow, that was fast!

thx a lot, we just tried and it works.

**Comment by alessiapacca** [comment]
hey @jagenjo , I tried to use
var graph = new LGraph(); 
graph.load(mypath);

Where _mypath_ is the path of the JSON file. 
However, my page always start empty (never loads the JSON graph). The graph is serialized and saved correctly. What am I doing wrong?

**Comment by jagenjo** [comment]
load requires to pass a url or a File object.

if you have the JSON object, parse it and then call graph.configure( object );

**Comment by benhar-dev** [comment]
We added the load and save functionality directly in to litegraph just to simplify our UI (we only need to call graph.save() or graph.load().  This is a small snippet from our monkey patch.

@jagenjo this is such an amazing piece of software.   Thank you for making this available!   

`
            LiteGraph.LGraph.prototype.save = function () {

                var data = JSON.stringify(this.serialize());
                var file = new Blob([data]);
                var url = URL.createObjectURL(file);
                var element = document.createElement("a");
                element.setAttribute('href', url);
                element.setAttribute('download', "untitled.tcgraph");
                element.style.display = 'none';
                document.body.appendChild(element);
                element.click();
                document.body.removeChild(element);
                setTimeout(function () { URL.revokeObjectURL(url); }, 1000 * 60); 

            }

            LiteGraph.LGraph.prototype.load = function () {

                var this_graph = this;

                if (typeof FileReader === 'undefined') {
                    console.log('File loading not supported by your browser');
                    return;
                }

                var inputElement = document.createElement('input');

                inputElement.type = 'file';
                inputElement.accept = '.tcgraph';
                inputElement.multiple = false;

                inputElement.addEventListener('change', function (data) {

                    if (inputElement.files) {

                        var file = inputElement.files[0];
                        var reader = new FileReader();

                        reader.addEventListener('loadend', function (load_data) {

                            if (reader.result)
                                this_graph.configure(JSON.parse(reader.result));

                        });
                        reader.addEventListener('error', function (load_data) {
                            console.log('File load error');
                        });

                        reader.readAsText(file);

                    }
                });

                inputElement.click();
                return;

            }
`

**Comment by jagenjo** [comment]
Ben created this nice solution, I don't know why he removed the comment from here, it was quite useful for others:

```js
LiteGraph.LGraph.prototype.save = function () {

            var data = JSON.stringify(this.serialize());
            var file = new Blob([data]);
            var url = URL.createObjectURL(file);
            var element = document.createElement("a");
            element.setAttribute('href', url);
            element.setAttribute('download', "untitled.tcgraph");
            element.style.display = 'none';
            document.body.appendChild(element);
            element.click();
            document.body.removeChild(element);
            setTimeout(function () { URL.revokeObjectURL(url); }, 1000 * 60); 

        }

        LiteGraph.LGraph.prototype.load = function () {

            var this_graph = this;

            if (typeof FileReader === 'undefined') {
                console.log('File loading not supported by your browser');
                return;
            }

            var inputElement = document.createElement('input');

            inputElement.type = 'file';
            inputElement.accept = '.tcgraph';
            inputElement.multiple = false;

            inputElement.addEventListener('change', function (data) {

                if (inputElement.files) {

                    var file = inputElement.files[0];
                    var reader = new FileReader();

                    reader.addEventListener('loadend', function (load_data) {

                        if (reader.result)
                            this_graph.configure(JSON.parse(reader.result));

                    });
                    reader.addEventListener('error', function (load_data) {
                        console.log('File load error');
                    });

                    reader.readAsText(file);

                }
            });

            inputElement.click();
            return;

        }
```

**Comment by benhar-dev** [comment]
Thanks @jagenjo, I took it down just as a precaution.  After reading the other comments I saw that you had implemented a .load() and hadn't yet checked to see what you had done.  I didn't want it to clash without checking your code first.  I'm pleased you like it.

@jagenjo litegraph is such a great piece of work! Thank you for making it available to us all.

**Comment by jagenjo** [comment]
@benhar-dev always share, the conversation is useful.

glad you like it.

**Comment by culurciello** [comment]
thank you this helps a lot
