### ISSUE TITLE
unknown number of inputs

### ISSUE THREAD

**Issue by RiccardoRossi** [jagenjo/litegraph.js#172]
hello,

i woukd like to concatenate a certain (u priori unknown) number of objects into a list.

how should i handle the input? is there any example including an unknown number of inputs?

**Comment by jagenjo** [comment]
you can creade a widget of type "button" that when clicked adds more inputs

and on your onExecute do a for(var i  = 0; i < this.inputs.length; ++i) and read every input

**Comment by RiccardoRossi** [comment]
ok thx
