### ISSUE TITLE
Slot removal trouble

### ISSUE THREAD

**Issue by atlasan** [jagenjo/litegraph.js#184]
Hi there :)

Being available the feature "Remove slot", and because many of the nodes access the input/outputs by Index, this lead immediately to problems when deleting a node that has another one following (the index are shifted) and many nodes cannot works without their slots.

What about placing an "optional" parameter to the slots, so the manually added slots would have it and they can be removed, while the main slots dont?

**Comment by jagenjo** [comment]
makes sense, I will give it a look

**Comment by alessiapacca** [comment]
Any update about this?

**Comment by jagenjo** [comment]
done

**Comment by atlasan** [comment]
You can take a look here:

https://github.com/atlasan/litegraph.js/blob/ea07dd164ef694acaf738b7d619883aaae4d1adb/src/litegraph.js#L13144

https://github.com/atlasan/litegraph.js/blob/ea07dd164ef694acaf738b7d619883aaae4d1adb/src/litegraph.js#L10775

**Comment by atlasan** [comment]
@jagenjo jagenjo closed this 20 seconds ago
 ops ^_^

**Comment by jagenjo** [comment]
✌
