### ISSUE TITLE
Sidepanel 'Delete' button does not trigger 'beforeChange' / 'afterChange' sequence

### ISSUE THREAD

**Issue by ralphwetzel** [jagenjo/litegraph.js#185]
Hi!
As stated: The 'Delete' button on the side panel does not trigger the 'beforeChange' / 'afterChange' sequence.

https://github.com/jagenjo/litegraph.js/blob/2fe197bb8bfc0dad3e80e4425b4be7bff1377509/src/litegraph.js#L10414-L10419

Is this a design 'by intension'? If not: Would you accept a PR to add this functionality?

**Comment by atlasan** [comment]
Seems that LGraphCanvas.onMenuNodeRemove do calls graph.beforeChange and graph.afterChange, while the panel button does not. It seems fine to add these two calls around the .remove() call.
Anyway as by https://github.com/jagenjo/litegraph.js/issues/30, the side panel is still under construction and is more an easy way to start with than a complete solution, it misses realtime values updates, title color and mode editing, along with fixes and improvements.

**Comment by ralphwetzel** [comment]
@atlasan: Even if it was addressed to you - there's no reason to answer with impudence. I just raised an issue offering support.


That said: Are you goping to back-feed the numerous & great changes you did for **litegraph.js** to [this (root) repository](https://github.com/jagenjo/litegraph.js) ... or do you intend to run an independent [fork](https://github.com/atlasan/litegraph.js)?

**Comment by jagenjo** [comment]
hi @ralphwetzel 

why beforeUpdate and afterUpdate? those are designed for when running the graph.
also as @atlasan said, the left panel is more an example, not much work put into it as I understand that the interface should be something everybody adapts to their site.

**Comment by ralphwetzel** [comment]
Hi @jagenjo!
I have to admit that I named the wrong function calls - was trying to reference `beforeChange` / `afterChange` => issue edited! :smirk:

Additional info: I am trying to implement a reliable undo functionality ... following your comment in the code:

https://github.com/jagenjo/litegraph.js/blob/1020176bc268f9b6f604987f9d78073aa7abd7db/src/litegraph.js#L1877-L1883

This works in many cases - yet there're a number of operations that do not call 'beforeChange' ... despite they change the graph. If I'm heading in the wrong direction, any hint for the right one is truly welcome!

**Comment by atlasan** [comment]
Not sure if doing right, I'll try again.
I've implemented an undo-redo and noticed what you comment @ralphwetzel : some place miss the event call.
An easy way to find many probable places is to look for "_version++" in the code.
What I've done is to add a name for the action that caused the change, so we could eventually build a history steps list from that.

ref:
https://github.com/atlasan/litegraph.js/commit/e5892ad12ec41370994f8e0984f33b0856a452c7
https://github.com/atlasan/litegraph.js/commit/936d232ca07664fa0d5f8a66c4f264aacdf34314

**Comment by ralphwetzel** [comment]
Hi @atlasan!
My approach is quite similar to yours - yet **working with** this library rather than **being (fully) integrated** into it.

To summarize @jagenjo: I'll issue PRs for those operations where `beforeChange` / `afterChange` calls are missing ... and keep this issue open until the job is done.

**Comment by jagenjo** [comment]
I just added the beforeChange and afterChange to the remove function.
but im not sure that is correct as I feel this was called from several places that already do this.

anyway, I have implemented undo in many projects that use litegraph without problem using those functions.

**Comment by atlasan** [comment]
If I can point it out, the suspicion is correct for this imlementation.
It seems to me that normally beforeChange and afterChange are implemented "a step higher" than the last level where the action is than taken.. I mean, usually the change is called at "interface level", not at action level.. I explain:
- it is not LGraph.prototype.add but all the methods that call it where before-after-Change are implemented
- it is not inside LGraphNode.prototype.removeInput, but again at upper level
- same for LGraph.prototype.remove, it is implemented in LGraphCanvas.onMenuNodeRemove

To resume: those two calls should be moved around the .remove in https://github.com/jagenjo/litegraph.js/blob/2fe197bb8bfc0dad3e80e4425b4be7bff1377509/src/litegraph.js#L10414-L10419 instead of inside the .remove method itself
