### ISSUE TITLE
[HELP] Multiline Text widget

### ISSUE THREAD

**Issue by iamrenaud** [jagenjo/litegraph.js#186]
Hello,

I would like to know if a multiline Text widget exists and how to create it if not.

Thanks!

**Comment by atlasan** [comment]
With a small change the actual text widget would already support that : prevent the "save" action on pressing enter if you hold SHIFT (or CTLR)
ref: https://github.com/atlasan/litegraph.js/blob/cbd9813d8234d4b4688c0746a8cfd8dd380b7659/src/litegraph.js#L12018

**Comment by iamrenaud** [comment]
Hey @atlasan, thanks for the reply. I'll try and see how it works.

**Comment by iamrenaud** [comment]
@atlasan 
I tried, but the Text widget always updates when I press ENTER.

**Comment by atlasan** [comment]
With that exact code you should press ENTER while holding SHIFT, that would make a new line (prevent the ENTER normal behaviour)

**Comment by iamrenaud** [comment]
@atlasan 
I'm likely doing something wrong then 🤔.
Does your fork have this feature enabled? Or could I have a working demo?

**Comment by atlasan** [comment]
Can't promise anything, but that code should work. I discurage using the fork I am working with.

**Comment by iamrenaud** [comment]
@atlasan
OK, thanks anyway.

**Comment by jagenjo** [comment]
I just uploaded a version that supports multiline:

```
	this.text2 = this.addWidget("text","Text", "multiline", function(v){}, { multiline:true } );
```

**Comment by atlasan** [comment]
Beautiful @jagenjo.
I'm sorry @iamrenaud I tought you were talking about the textWidgetNode.
^_^
