### ISSUE TITLE
Anuglar 8: Styles not processed

### ISSUE THREAD

**Issue by Hydhen** [jagenjo/litegraph.js#188]
I've downloaded the npm package inside my Angular 8 project

The JS part seems to work as expected, at least for my needs, but the whole CSS isn't processed
I tried to moved the CSS code inside my components .css file to see if that was an import issue, I also added a simple rule:

```css
h1 {
  background-color: blue;
}
```

My h1 has the style affected but the litegraph right click menu is not

![image](https://user-images.githubusercontent.com/3842750/103994502-62892a00-5197-11eb-98ae-168e57234332.png)

I wonder if it has something to do with the menu creation which is injected into `document`

1. What can I do to make styles work properly, otherwise
2. How to disable the right click menu so i can use my webapp interface to interact with the litegraph

**Comment by jagenjo** [comment]
I dont have any experience in Angular, but that error is because it is not applying the CSS, that could happend only if:
- the CSS is not included in the HTML
- the menu element is not inside the DIV that contains the graph.
Compare it with my working version to see where is being added the menu:
https://www.tamats.com/projects/litegraph/editor/

**Comment by Hydhen** [comment]
I guess CSS is included like my title is updated

From what I can see in your version i don't see the menu inside the graph div either or i'm missing something

Here's my webapp document debug:
![image](https://user-images.githubusercontent.com/3842750/104007539-640f1e00-51a8-11eb-9ddc-4dcd60796357.png)

Here's yours:
![image](https://user-images.githubusercontent.com/3842750/104007753-b6503f00-51a8-11eb-89c1-2e35b9e1e39f.png)

In both case the div is added at the end of the body or am I missing something ?

**Comment by jagenjo** [comment]
true, sorry, I totally forgot that I changed that some time ago.

so then the CSS is not being added, as the rendering of the graph doesnt use the CSS, only the menu use the CSS.

**Comment by Hydhen** [comment]
I got inspired and though about the whole Angular component mecanism and in fact, each component has an encapsulation policy for styles to protect styles to overrides themselves on bigger webapp

Here is the trick, in your component that manage the graph you have to specify to not use an encapsulation policy by doing adding an `encapsulation` property to the component like so:
```typescript
@Component({
  selector: 'app-litegraph',
  templateUrl: './litegraph.component.html',
  styleUrls: [
    './litegraph.component.scss'
  ],
  encapsulation: ViewEncapsulation.None
})
```

But there's still something I cannot explain, why my h1 style has been affected properly but not the litegraph css rules
Anyway issue solved ! :)
