### ISSUE TITLE
onPropertyChanged not defined/triggered

### ISSUE THREAD

**Issue by Hydhen** [jagenjo/litegraph.js#189]
I try to setup a node with a RegularExpression

So far I got my node with a widget for the pattern, an input and an output

![image](https://user-images.githubusercontent.com/3842750/104017048-b572d980-51b7-11eb-8509-89c3a46e8be2.png)
![image](https://user-images.githubusercontent.com/3842750/104017030-ab50db00-51b7-11eb-9c07-3511d5b99f40.png)

NB: I had autocompletion for the `onExecute`, but nothing for `onPropertyChanged` and yet nothing happens in my console

What i'd like is the node (or the little top left knot) to turn to a redish color when the RegExp is invalid

What i need is access to the callback onPropertyChanged which is not defined in `litegraph.d.ts`
I might want to call it in the wrong scope I'm a bit confused

**Comment by jagenjo** [comment]
A widget is not a property, but you can link them if when defining the widget you pass as the fourth parameter the name of the property.
