### ISSUE TITLE
slot not defined

### ISSUE THREAD

**Issue by brucelane** [jagenjo/litegraph.js#19]
Olà!
I run litegraph demo on my local machine in Chrome 64.
I'm trying to use my nanoKontrol2, it is seen, but I don't see the midi messages.
And slot is undefined as seen on the image.
![image](https://user-images.githubusercontent.com/138158/37071850-da97dde0-21be-11e8-9998-acdc15bdb6cc.png)

Congratulations for this software!

**Comment by brucelane** [comment]
I get "trigger on_midi0. CC 14 65" from LGraphNode.prototype.trigger = function( action, param ) line 1806 though, but "slot" on line 1816 is undefined

**Comment by jagenjo** [comment]
ups, I changed that some days ago, I fixed it. thanks for the warn.

**Comment by brucelane** [comment]
I did a PR for the last bug! https://github.com/jagenjo/litegraph.js/pull/21

**Comment by brucelane** [comment]
![midifix](https://user-images.githubusercontent.com/138158/37110407-17b8378c-223d-11e8-856a-dde61c0a7f73.jpg)
now it works!

**Comment by jagenjo** [comment]
nice, I havent finished the MIDI nodes, let me know which features you find missing
