### ISSUE TITLE
litegraph.d.ts not up to date ?

### ISSUE THREAD

**Issue by Hydhen** [jagenjo/litegraph.js#193]
I have this error in my VSCode:

![image](https://user-images.githubusercontent.com/3842750/104581426-dd05ee00-565e-11eb-9cc4-6e9c9b415106.png)

Since it's a typescript error I think the litegraph.d.ts is not up to date but I might be wrong

The feature still work, only a visual and compile error happens

**Comment by atlasan** [comment]
Empty string "" have the same behaviour as 0, you could try with that

**Comment by Hydhen** [comment]
Oh you're right!

Maybe add a small note to `addInput` would be great

Thanks !
