### ISSUE TITLE
delete/deselect nodes question

### ISSUE THREAD

**Issue by HeSe** [jagenjo/litegraph.js#2]
Hi!

I have two questions.

Why is it necessary to set the node.id to -1 in LGraph.prototype.remove = function(node)?
I have implemented a onNodeRemoved(node) in my editor and the id is set to -1 my editor does not more find the particular node in it's own node collections.

Why does onNodeDeselected() not have a parameter? I changed it to onNodeDeselected(n) in all calling parts in litegraph.js in order to have my editor to be able to react on deselection of particular nodes.

Well, great work by the way. I think I will soon add some minor pull requests once I understand your intentions a little better.

Thanks
Sebastian

**Comment by jagenjo** [comment]
You are right, the -1 I guess comes from when the very beginning when the id was the position in the nodes array, but thats no longer true so I removed the line.
I also added the node on onNodeDeselected. :)

**Comment by HeSe** [comment]
Thank you! 
And one more since we are at it....

How do you use the node methodes onDeselected/onSelected.
I find it difficult to access those to define behavior on Node level.
Do you have an example you can point at?

**Comment by jagenjo** [comment]
What do you want to do? to use you must just add a callback in the node:
this.onSelected = function() { ... }
