### ISSUE TITLE
feature request: websocket client

### ISSUE THREAD

**Issue by brucelane** [jagenjo/litegraph.js#20]
I would like to add websocket support, so it would imply at least 2 more nodes:

- websocket server ip, port, a ws/wss toggle, connect button
- websocket sender

Eventually a websocket receiver.

What do yo think?

**Comment by jagenjo** [comment]
ok, I added the network/websocket component, it allows to send different data through different channels.
I also added a network/sillyclient that connects to a sillyserver which bounces packets back to all connected users, for more info: https://github.com/jagenjo/SillyServer.js

I havent tested the websockets one, but the sillyserver works perfectly

**Comment by brucelane** [comment]
thank you for the websocket support, I would like it to send data from knobs, sliders, etc.
It seems it only supports some room chat messages right now.

**Comment by jagenjo** [comment]
are you using the sillyserver or the websocket?

**Comment by brucelane** [comment]
your websocket module with my nodejs websocket server, this works fine:
```
this._ws.onopen = function()
	{
		console.log("ready");
		that.boxcolor = "#8E8";
		that._ws.send( JSON.stringify({ type:1, msg: "data" }) );
	}
	this._ws.onmessage = function(e)
	{
		console.log("_ws.onmessage" + e);
```

**Comment by brucelane** [comment]
so how can I send a websocket message when I change the slider value?

**Comment by jagenjo** [comment]
just plug the slider value to the IN field in the websocket node and press play
it will send a message every time it detects the value has changed.

**Comment by brucelane** [comment]
yes, easy one, sorry!
I had to rework my websocket server code to match your incoming messages.
It seems that messages are always sent even if the slider value doesn't change.
I would need to add an output to the text node to send the text via websocket.

**Comment by jagenjo** [comment]
I uploaded a version yesterday that has the "only send changes" which will only send the data if it changes. Update to the newer version to get the changes.
