### ISSUE TITLE
Make MAX_NUMBER_OF_NODES configurable

### ISSUE THREAD

**Issue by dsebastian** [jagenjo/litegraph.js#208]
Hi, I recently started playing with the library and it seems promising.
There seems to be a hard limit of 1000 due to MAX_NUMBER_OF_NODES property. I managed to go around it by overwriting it directly ( LiteGraph.MAX_NUMBER_OF_NODES = 9999 for example) and the graph works well due to rendering do Canvas (even if the number of nodes is over 1000). Is there any reason why this limit is in place or a better way to make this configurable? (in the code I see the  //avoid infinite loops but don't know where this originated from or how it can be reproduced to make sure I don't hit this problem)
Thanks

**Comment by jagenjo** [comment]
no, just inscrease it as you wish, I added in case somebody was adding nodes cosntantly without knowing and crashing the browser.
