### ISSUE TITLE
Ability to create custom widgets

### ISSUE THREAD

**Issue by dsebastian** [jagenjo/litegraph.js#209]
Hi, 

The current system for creating widgets seems to be quite limited as the type is hard locked to a few widgets, who's content/appearance can't be easily changed as it's all coded in drawNodeWidgets function. There is an addCustomWidget function that with some types hacking can be used to add additional functions as widgets, but the issue is that the "if (w.draw)" on line 8796 that is supposed to draw them never passes, as the widgets are transformed into objects and thus loose their prototype by this point (though I can't pin point where).

Do you have any example on how to use addCustomWidget or another way to add custom widgets that can be built and reused in different nodes? The only way I see currently around this would be to not use Widgets at all and draw directly inside the node's functions (for example in onDrawBackground). But then you would probably loose the automatic calculations.

Thanks.

**Comment by jagenjo** [comment]
seems like a bug, I will check, but remember that a node can capture any mouse event and you can define how a node is rendered, so nothing stops you to bypass the widgets system and create your own interface in nodes.

**Comment by dsebastian** [comment]
Yes, I can probably draw them inside the node, but my thought process was to do it via the normal route which has a certain order established. For example drawNodeWidgets is inside drawNode and there's code before and after that does several calculations related to Y pos and height that I thought could be useful. 

In any case, if there is a way to not have the node.widgets transformed to objects such that they loose all Prototype functions, let me know. Thanks.
