### ISSUE TITLE
How to have Editor in codepen?

### ISSUE THREAD

**Issue by j2l** [jagenjo/litegraph.js#219]
Hello,
Studying your demo, I tried to have the editor running in codepen, see JS & CSS libraries in https://codepen.io/j2l/pen/abpdgvM
Editor doesn't show up though.
What am I missing?

**Comment by jagenjo** [comment]
You need to use LGraphEditor:
https://github.com/jagenjo/litegraph.js/blob/master/src/litegraph-editor.js

**Comment by j2l** [comment]
Thank you,
Hmmm, that's waht I've done AFAIK, in my settings, for JS libraries, I have:
https://cdn.jsdelivr.net/npm/litegraph.js/build/litegraph.js
https://tamats.com/projects/litegraph/src/litegraph-editor.js

**Comment by j2l** [comment]
I also tried by copying your file and running it locally with:
    <script type="text/javascript" src="./litegraph-editor.js"></script>
in the body, but nothing shows up.
