### ISSUE TITLE
Feature request: Pan around the viewport with W,A,S,D or connected link location

### ISSUE THREAD

**Issue by theycallmeloki** [jagenjo/litegraph.js#220]
First off, this is an excellent library and I really like how easy it was to modify and monkeypatch it for custom requirements, 

I have a suggestion, when there are too many nodes that have been programatically drawn, a node on the far left might need to connect to a node on the far right, the way I am doing it now is to click on the source node, zoom out and eyeball the connection point on the right 

A way this could be improved is by adding the ability to pan using WASD, that way I can click on the source node's source slot, pan to the right using 'D' until I find the connection point and drop it on the target slot 

An alternative to this could be if a connection is being actively drawn and if the user reaches 5% margin from the top, left, right or down of the viewport, then the viewport can be delta'd by that that direction, so I can click on a source node's source slot, move right and as soon as I've hit a particular threshold (5% from the right) on the viewport, the viewport pans to the right until I bring the mouse back to mean position thereby allowing me to pick the target slot 

Any tips on how to start on either of these problems would be awesome 

Keep up the amazing work! :D

**Comment by jagenjo** [comment]
Thanks!

The deltaing when on margin makes sense, meanwhile you can hold SPACEBAR to pan without releasing the mouse.
Cheers
