### ISSUE TITLE
Info for custom node 

### ISSUE THREAD

**Issue by fedeMarcantognini** [jagenjo/litegraph.js#224]
Hi there,
for information only - assuming a very specific use case where data between nodes is _limited to float type only_, would it be possible to have a custom node that has inputs and output ports/sockets on both sides of the node (something close to the image below)? Each output port should have editable fields with percentage values.

<img width="718" alt="Node-example" src="https://user-images.githubusercontent.com/19288193/114069136-f1910580-989e-11eb-9099-2d00598693c0.png">

Grateful if you can advise, thank you!

**Comment by jagenjo** [comment]
you can code it yourself by changint the function that renders the content of the node: onDrawBackground

about multiple links to the same input, the answer is no.
