### ISSUE TITLE
Order of execution doesn't keep track of priority or position

### ISSUE THREAD

**Issue by EnricoPietrocola** [jagenjo/litegraph.js#226]
I would like to set the order of execution of multiple nodes connected to the same output of a main node. 
I would like to have them respect a left to right order of execution (I am using flat slots), so that if I move a node to the left of another, it will be executed before the other. 

I realized I can use the this.pos variable to understand where the node is, but how could I get an array of all connected nodes to a node and then organize execution based on position?

**Comment by derrell** [comment]
It looks like there is a `priority` member of a node class, and if not found there, the option of a `priority` member of a specific node instance. The final step in `LGraph.prototype.computeExecutionOrder` is to sort the nodes by `priority`, and then by the internally-ascertained order. You can try adding a `graph.on_change` handler, and calculating priority based on nodes' positions. Alternatively, you could override `computeExecutionOrder` to take position into account while calculating that order.

I'm just a (fairly new) user of this package, not a developer of it. There may be better options that others can suggest.

**Comment by EnricoPietrocola** [comment]
Hi @derrell!
I am testing with priority and managed to get priorities set on pos[0] (x axis), but the execution order won't change anyway. Still trying to figure out why, I'm sure my calculation is right and I tried inverting values to see if by chance priority was given to the lower value, but it didn't really change. The only changes I can see are when I delete a link and create a new one

**Comment by EnricoPietrocola** [comment]
I tried printing a bit of consoles from the src code and I can see that computeExecutionOrder (and update execution order) return an array sorted as I would expect, but then the actual order of execution of my nodes doesn't really reflect the array's order

**Comment by EnricoPietrocola** [comment]
Could it be that I am using onAction and sorted nodes only count on onExecute?

**Comment by EnricoPietrocola** [comment]
I did more testing and I can confirm that priority only works on onExecute, which would be fine to me if it wasn't that priority completely overrides order of execution on all nodes, not only nodes on the same level. This way I seem to get my last nodes executing before the very root nodes

**Comment by jagenjo** [comment]
order is only considered in onExecution as that one iterates through all nodes so we can control the order.
onAction is triggered by events, so I cannot control the order.
