### ISSUE TITLE
Uncaught TypeError: this.getCanvasWindow is not a function

### ISSUE THREAD

**Issue by Eikeike** [jagenjo/litegraph.js#234]
This error appears in the console when you try using Litegraph with touch events. It's in [line 9156 of litegraph.js](https://github.com/jagenjo/litegraph.js/blob/bfaafe952616be24e9698454c121edff06215c3f/src/litegraph.js#L9156)

**Why:**

Because touchHandler is a callback that is bound to the canvas as an event listener, `this` refers to the DOM-Element this listener is attached to. It should point to the LGraphCanvas. 

**Quick fix:**

Replace `this` with `LGraphCanvas.prototype` inside of the `touchHandler`-Function. It's not beautiful, but it works. 

You could also think about permanently replacing `this.touchHandler` by `this.touchHandler.bind(this)` _before_ binding it in the [binEvents-Function](https://github.com/jagenjo/litegraph.js/blob/bfaafe952616be24e9698454c121edff06215c3f/src/litegraph.js#L5003). Pay attention to unbinding it correctly though.

**Comment by jagenjo** [comment]
Fixed in the last commit

**Comment by gausszhou** [comment]
> Fixed in the last commit

Are you considering releasing a new version to npm? :blush:

**Comment by jagenjo** [comment]
published

**Comment by gausszhou** [comment]
> published

thankyou very much 😊
