### ISSUE TITLE
Mixing horizontal and vertical inputs.

### ISSUE THREAD

**Issue by MegaIng** [jagenjo/litegraph.js#237]
Is there a way to have one node type to have inputs/outputs on the top/bottom and from the side? If not, would it be possible to add that?

(For me it might be even be useful to be able to drag pins to any position on the noed the user likes, but I think that is quite a lot more to ask for)

**Comment by atlasan** [comment]
One important thing is visually understand the data flow, having mixed positions would make this hard or confusing.
Overriding the drawNode function you could implement a custom visualization like custom pin placement, but be sure to implement a visual feedback for the slot direction so one could easily see where data is coming-going.

**Comment by jagenjo** [comment]
You can manually place the slots from code, but as @atlasan said, if there are inputs on the right side it will be hard to read the data flow.

**Comment by MegaIng** [comment]
My primary idea was to have control flow run from top to bottom, and to have data flow go left to right.

**Comment by jagenjo** [comment]
yeah, that is possible, set up position of inputs:

```
this.addInput("name","type",{ position: [0,100] } );
```

**Comment by atlasan** [comment]
> 
> 
> My primary idea was to have control flow run from top to bottom, and to have data flow go left to right, but thank you.

That's an interesting idea!
With many nodes it's normal (to me) to have left to right and top to down arrangements mixed. Many times you get a value from a node and you would use that out slot as data input in a node following, as the execution line would normally do, so probably they will get mixed anyway drawing strange patterns, but in some arrangement that could works good.
Maybe, eventually with the aid of a diagonal split of the node, with left and top for IN and right and down for OUT with movable slots could be interesting.
Share some pictures if you make something interesting and you are willing to. ^_^
