### ISSUE TITLE
Cannot set property deltaX of #<WheelEvent> which has only a getter

### ISSUE THREAD

**Issue by L1nY4n** [jagenjo/litegraph.js#238]
I'am trying migrate the editor-demo to my vue appliction and got the console error 
``` Uncaught TypeError: Cannot set property deltaX of #<WheelEvent> which has only a getter
    at LGraphCanvas.adjustMouseEvent (litegraph.js:6613)
    at LGraphCanvas.processMouseWheel (litegraph.js:6041)
``` 
it seems cause by javascritpt 'strict mode' ?  how can I fix this🤣

**Comment by nab-os** [comment]
How is this "Closed" ?
We still have the issue.
A workaround is not a fix
I am missing something ?

**Comment by ghiscoding** [comment]
I got that problem while trying the lib and it seems that it got fix latest with this [commit](https://github.com/jagenjo/litegraph.js/commit/ab9ca1afe2938dc9a7ce1676d98b94e05baae8fc), however it's not yet released under a new version

**Comment by L1nY4n** [comment]
Good to know 😹

**Comment by L1nY4n** [comment]
fix in [#287](https://github.com/jagenjo/litegraph.js/pull/287)

**Comment by Plaximo** [comment]
Unfortunately by removing this lines, the number widget is not working anymore. I'm receiving NaN if I drag the value.

**Comment by KaKi87** [comment]
I tried using `git+https://github.com/jagenjo/litegraph.js#ab9ca1afe2938dc9a7ce1676d98b94e05baae8fc` as dependency but the error still occurs
