### ISSUE TITLE
Why is it designed like this?  delta * 0.1

### ISSUE THREAD

**Issue by gausszhou** [jagenjo/litegraph.js#239]
```js
this.freq_widget = this.addWidget(
    "number",
    "Freq",
    this.properties.freq,
    "freq",
    { min: 1, max: 100, step: 1 }
  );
```
Actually the step is 0.1

https://github.com/jagenjo/litegraph.js/blob/master/src/litegraph.js#L8917

Why is it designed like this?
```
w.value += delta * 0.1 * (w.options.step || 1); 
```

**Comment by mcejp** [comment]
Hi @gausszhou, I'm scratching my head over this as well. What conclusion did you reach?

I'm looking for a way to constrain a parameter to (positive) integers only.

**Comment by jagenjo** [comment]
because the delta is in pixels, so 10 pixels equal to one step

**Comment by mcejp** [comment]
@jagenjo Thanks for your reply and for your work on this great library.

Would you consider a merge request that adds an option to force the edited property to always be an integer multiple of `step`?

**Comment by jagenjo** [comment]
Sure

**Comment by mcejp** [comment]
This would make even more sense for the `slider` widget, where the implementation is really obvious.

I'm wondering what to call the new option, though, since `step` is already being used to represent _sensitivity_, which is a very different concept. Any suggestions?
