### ISSUE TITLE
The drawing of ROUND_SHAPE is strange

### ISSUE THREAD

**Issue by gausszhou** [jagenjo/litegraph.js#250]
- ROUND_SHAPE
![image](https://user-images.githubusercontent.com/46297500/128798827-c7b1e0f3-64ef-407b-86d8-3434c685628b.png)

**Comment by jagenjo** [comment]
yeah, I did a commit today, I hope it fixes it.

**Comment by gausszhou** [comment]
> yeah, I did a commit today, I hope it fixes it.

Great job ！This solved my problem.
