### ISSUE TITLE
Is it possible to have output sockets on both sides of a node?

### ISSUE THREAD

**Issue by lucian-rus** [jagenjo/litegraph.js#252]
Dumb question as I am just starting with node-based UIs, but I was wondering if there is any way to have output sockets on both sides of a node, assuming that I want a node to have a really large number of possible outputs. Below is an attachment of what I'm trying to achieve.
![image](https://user-images.githubusercontent.com/51233586/129620412-dcc022cc-f7a5-4d5a-905f-042f95d1ebd1.png)

**Comment by jagenjo** [comment]
nop, that would be confusing.
