### ISSUE TITLE
Multiple output connected to same input

### ISSUE THREAD

**Issue by coollofty** [jagenjo/litegraph.js#253]
I took a look at the code, and it seems that there is no option that can achieve this function. I also tried to modify the code, commenting out the 3723-3727 lines, but it did not have any effect. How should this need be solved?

**Comment by benhar-dev** [comment]
The issue with having multiple outputs on the same input is that you would not have any common way to handle how it is processed, i.e. should the inputs be treated as an array of individual inputs and the node executed multiple times, should the inputs be combined, should the first win.  

We tackle this with making "signal combining nodes" which have multiple inputs and a single output which can then feed the node in question.  We then have full control how these values are handled.

**Comment by alessiapacca** [comment]
Hi @benhar-dev , could you please explain a bit more in depth how you made signal combining nodes?

**Comment by jagenjo** [comment]
create nodes that have several inputs and one output, and code the node to handle the mixing of all signals.

**Comment by alessiapacca** [comment]
@jagenjo @benhar-dev what if I don't know the number of inputs the user wants?
I know the user can add slots as he wants, but this would mean that if the user wants to input N objects, with a big N the node would become huge. 

The merge node is interesting, but it still doesn't allow to connect multiple inputs to the same slot..

**Comment by alessiapacca** [comment]
or maybe, it would be nice to connect multiple inputs to the slot of the array node.
This way we would have an array of inputs as output of the node

**Comment by jagenjo** [comment]
as we said, the whole library is coded asuming one single input per slot, changing that would require a huge coding effort.

**Comment by gausszhou** [comment]
> The merge node is interesting, but it still doesn't allow to connect multiple inputs to the same slot..

You can define a special slot on the node, link this slot, automatically add an input slot and connect
