### ISSUE TITLE
Callback for every time an input is changed?

### ISSUE THREAD

**Issue by alessiapacca** [jagenjo/litegraph.js#254]
If I have a node with N input ports and I want to detect every time one of them changes value, which callback can I use?

**Comment by jagenjo** [comment]
you must code the node function onExecute, that will be executed on every step, and use that function to read the inputs and do whatever you want to do.

there is no default method to detect changes, just read the inputs yourself and do what you need. Thats what all nodes do.

**Comment by alessiapacca** [comment]
Hi @jagenjo , thanks for your answer. 
So isn't onConnectionsChange useful for this purpose?
Maybe I understood it wrongly, but isn't it executed every time an input connection changes?

**Comment by jagenjo** [comment]
wait, you mean wires change or the value from the wire change?
if you mean the first one, then yes, onConnectionsChange is called when wires are connected or disconnected.

**Comment by alessiapacca** [comment]
@jagenjo I meant value from the wire change, but without that possibility I can assume that you need to change the value from the wire when it is disconnected and then connect it again to our node. 

Perfect thank you very much. 
I actually have another question: can I add input ports to my node only after reading one initial port value? Let's say I want the number of input ports to be dependent on the initial port value. 
How would you do that?
I am trying to figure out which callbacks may be useful for this.

**Comment by atlasan** [comment]
Hi @alessiapacca, probably you want to check your first input slot value every frame (node execution), when the value changes you can add or remove extra input slots. No callbacks are needed for this. Nodes themselves add slots (nodex.addInput("NAME", "TYPE")) and you can remove 'em too with removeInput(slotNum).

**Comment by alessiapacca** [comment]
Ok thanks @atlasan for the insights. It is however strange cause if I do:

```
MyAddNode.prototype.onExecuted = function() {
  var inp = this.getInputData(0);
  if(inp == undefined){
    this.addInput("Undefined", "String");
  }
  else {
    this.addInput("Defined", "String");
  }
}

```

Nothing happens on the node.

**Comment by jagenjo** [comment]
weird, that should create endless inputs until it crashed your browser as you are adding inputs on every step (the graph executed 60 steps per second)

are you running the graph with the play button?

**Comment by atlasan** [comment]
`	// dynamic inputs
    function DynInputs() {
        this.addInput("nInputs", "");
    }

    DynInputs.title = "DynInputs";
    DynInputs.desc = "DynInputs";

    DynInputs.prototype.onExecute = function() {
        var v = this.getInputData(0);
		if(v)
		{
			if(Number(v)>this.inputs.length){
				for(var nI=this.inputs.length-1; nI<v; nI++) this.addInput("slot"+(nI+1),"myType");
			}else if(Number(v)<this.inputs.length){
				for(var nI=this.inputs.length-1; nI>v; nI--) this.removeInput(nI);
			}
		}
    };

    LiteGraph.registerNodeType("example/dynInputs", DynInputs);`
   
   You can try this (with play button on ^_^)

**Comment by alessiapacca** [comment]
Ahhh it was a very stupid error: I wrote onExecuted instead of onExecute.
Now it works.
Thank you both for the help :)

**Comment by jagenjo** [comment]
I encourage you that if you plan to add inputs based on data arriving, you use the Events system, events are created for situations that happen sometimes.

Also it is possible to add buttons in the node to add more inputs on demand, using widgets or the contextual menu.
