### ISSUE TITLE
Question regarding the extra_info parameter

### ISSUE THREAD

**Issue by alessiapacca** [jagenjo/litegraph.js#255]
The parameter **extra_info** from functions like _addInput_, _addOutput_, is an Object.
The documentation says this can be used to have special properties of an output (label, special color, position, etc).
But what is the sintax to specify the position extra_info?
For example, is there a way to specify **right/left** for the port I am inserting on the node?

**Comment by alessiapacca** [comment]
**or**: did it ever happened to anybody that the function _addOutput_ adds an input slot instead?

**Comment by jagenjo** [comment]
inputs are always left (or up), outputs right (or down).

the syntax to change position is:

addOutput("name","type", { position: [x,y] } )
