### ISSUE TITLE
Context menu with text input?

### ISSUE THREAD

**Issue by alessiapacca** [jagenjo/litegraph.js#257]
Let's say I have a context menu with a list of items.
I want the user to be able to add items to the menu (add an element to the list) if he wants to. 

So I though of one menu entry "_AddInput_" that, if pressed, makes a text editor appear (very similarly to the text widget). Once that the user inserts the text and presses ok, the new item appears on the menu. 

Now, my question is, once I have my _inner_clicked_ callback, how could I implement a text editor appearance?

**Comment by jagenjo** [comment]
there is a function in LGraphCanvas to prompt simple text:
https://github.com/jagenjo/litegraph.js/blob/master/src/litegraph.js#L9750

Also you can add easily more options to the context menu of a node with the node.getExtraMenuOptions callback.
