### ISSUE TITLE
Getting errors while using few widgets

### ISSUE THREAD

**Issue by AztrexDX** [jagenjo/litegraph.js#260]
Hi,

When certain widget are used like slider, range etc. getting errors in console. Sometimes over long time application starts hanging even after deleting nodes. May be this could be reason. The count keeps increasing.
![image](https://user-images.githubusercontent.com/86340924/135449877-ca6e0694-fc9f-4bab-9728-87eb47917e88.png)

**Comment by jagenjo** [comment]
these widgets are not official, do not know where they come from as they are not in this repo.

**Comment by AztrexDX** [comment]
Thanks for info
