### ISSUE TITLE
Is it possible to remove multiple nodes selected?

### ISSUE THREAD

**Issue by alessiapacca** [jagenjo/litegraph.js#265]
Let's say I have a selection of 10 nodes. At this point, if I right click and click "Remove", it only removes the node on top of which I  right clicked. Is there a shortcut that allows to delete the entire selection of nodes?

**Comment by jagenjo** [comment]
should be "delete" key

**Comment by atlasan** [comment]
@alessiapacca the delete key should work If you haven't changed key listeners or others core parts. The menu actions acting on a multiselection can be archived overriding the single methods or the whole menu.

I assume that this code should work for you:
```
LGraphCanvas.onMenuNodeRemove = function(value, options, e, menu, node) {
        if (!node) {
            throw "no node passed";
        }
		var graph = node.graph;
		graph.beforeChange();

		var fApplyMultiNode = function(node){
			if (node.removable === false) {
				return;
			}
			graph.remove(node);
		}
		var graphcanvas = LGraphCanvas.active_canvas;
		if (!graphcanvas.selected_nodes || Object.keys(graphcanvas.selected_nodes).length <= 1){
			fApplyMultiNode(node);
		}else{
			for (var i in graphcanvas.selected_nodes) {
				fApplyMultiNode(graphcanvas.selected_nodes[i]);
			}
		}

		graph.afterChange();
        node.setDirtyCanvas(true, true);
    };
```

I have some spare time and I'm quite in love with LiteGraph, in case you are in a paid project and need some help.

**Comment by jagenjo** [comment]
Control and Alt are detected from the mouse event, not the keyboard event so my guess is that the keyboard event is not binded or other element is stealing the focus.

Search for the event listener "keydown" to see if it gets binded.

**Comment by alessiapacca** [comment]
@jagenjo @atlasan  at the end I saw that it was triggering "_keyup_" and not "_keydown_" as it was supposed instead to do. 
I tried to use "_document_" instead of "_canvas_" just like you did for the keyup event listener and now _keydown_ gets triggered.
Just out of curiosity, why did you, in the first place, added the keyup event listener to the document and not to the canvas?

**Comment by jagenjo** [comment]
because if the canvas wasnt clicked then it wont be received. But it can be changed.
