### ISSUE TITLE
Select Area by holding left click

### ISSUE THREAD

**Issue by gotwig** [jagenjo/litegraph.js#27]
Like in unreal engine 4 blueprints, a user should be able to do the following:

Click on a point in the graph, hold left click and move the mouse to create a select area to select multiple nodes easily trough the select area

This way you can manage multiple nodes much more easily.

**Comment by jagenjo** [comment]
you can, by holding the control key. I added that feature last month.
Maybe I will add a mode to switch between dragging or selecting multiple
