### ISSUE TITLE
How to only use my own custom nodes?

### ISSUE THREAD

**Issue by gkgkgkgk** [jagenjo/litegraph.js#274]
How do I disable the categories/included nodes and only use the ones that I have created?

Thanks!

**Comment by gausszhou** [comment]
You can use this method to clear all default nodes

```js
LiteGraph.clearRegisteredTypes()
```
And you can also filter your nodes by  `graph.filter`

```js
this.graph = new LGraph();
this.graph.filter = "is_top_graph"
```

```js
if(this.canvas.graph != this.graph){
  this.canvas.graph.filter = "is_sub_graph"
}
```

**Comment by gkgkgkgk** [comment]
@gausszhou Thanks!
