### ISSUE TITLE
Undo feature

### ISSUE THREAD

**Issue by alessiapacca** [jagenjo/litegraph.js#275]
Hey @jagenjo , I was playing around with the callback OnBeforeChange. I keep track of a queue of graphs every time OnBeforeChange is called. I added an OnUndo callback, which is called when the user wants to undo the last change. In this OnUndo callback I just configure the last entry of the graphs queue. 

However, it happens that, when I undo a certain change, if this change is a new connected link, then the links gets deleted (and this is expected), but the slots keep staying green. So basically the links are not rendered anymore, but they stay in the graph (I checked the graph and they do not get removed from it).
Do you have any clue of why this may happen?

**Comment by jagenjo** [comment]
Hi Alessia:
How do you undo the change? Which sequence of commands do you do?

**Comment by alessiapacca** [comment]
I detect the ctrl Z key, I call the OnUndo callback, this OnUndo callback does: 

`graph.configure(graphPrevious.pop());`

graph previous is a N-sized queue with the serialized graphs stored (stored when OnBeforeChange is called).

**Comment by jagenjo** [comment]
Seems correct, thats who I do it in WebGLStudio.
Try this: stringify the previous graph json when storing, and parse it when configuring it.
My concern is that inside the last graph there are still some objects that are in use by the current graph.

**Comment by alessiapacca** [comment]
nice thanks now it works!
As you said, when OnBeforeChange is called I store `JSON.stringify(g.serialize())`, while when OnUndo is called I pop the last element and parse it

**Comment by jagenjo** [comment]
Cool, I guess we have to recheck the serialization process as some objects are not being cloned properly.

**Comment by alessiapacca** [comment]
@jagenjo yes, indeed also when I clone a node the links on the new node are not rendered but the slots stay green

**Comment by jagenjo** [comment]
@atlasan could this be related to anything from your changes? that cloning inputs and outputs is not done properly

**Comment by atlasan** [comment]
I had a similar issues, and some strange behaviors are present in my history implementation too.
So, you point out that probably the objects are not serialized/restored correctly? I don't think is one of my changes, but we have to check it.

**Comment by atlasan** [comment]
I had couple tries, and it seems to me that this could be the issue

```
o.inputs = LiteGraph.cloneObject(this.inputs); //this.inputs;
...
o.outputs = LiteGraph.cloneObject(this.outputs); //this.outputs;
```

this solve the issue in my case, not sure if that is correct. @jagenjo ?

before 
![2021-11-19 09_23_10-WinMerge -  dbg_serialize_historystep1 json - dbg_serialize_historystep1_backFro](https://user-images.githubusercontent.com/15611089/142598563-b8057145-8a9b-419c-8ba7-d236961fbe02.png)

after
![2021-11-19 10_23_59-WinMerge -  Untitled left - Untitled right](https://user-images.githubusercontent.com/15611089/142598578-20ad8531-e7c3-42ac-904d-42c796047596.png)

**Comment by jagenjo** [comment]
what concerns me is any of these arrays is not cloned, I will keep investigating
