### ISSUE TITLE
Background changes color when I zoom in and out

### ISSUE THREAD

**Issue by gkgkgkgk** [jagenjo/litegraph.js#276]
When I zoom out, the background fades to white. Any idea why this may happen?

![gifbg](https://user-images.githubusercontent.com/16886433/142498966-68f6b479-fa2f-4270-bd2e-3fcf65742279.gif)

I am using a react frontend, and my canvas is served like this:
`return (
    <div className="App">
      <canvas ref={canvasRef} id='mycanvas' width='1024' height='720'></canvas>
    </div>
  );`

**Comment by jagenjo** [comment]
set the div background to a gray color as the pattern texture fades to transparent.
