### ISSUE TITLE
Is it possible to get output id from node?

### ISSUE THREAD

**Issue by NickHatBoecker** [jagenjo/litegraph.js#277]
Hey there,

I'm trying to achieve the following:
I have a graph of game events. For example: Show a textbox, then show another Textbox.

This is my graph:
![](https://bilderupload.org/image/fc7993250-screenshot-2021-12-01-215.jpg)

And I need the following code result:

```js
[
    {
        id: 1,
        type: 'game/textbox',
        next: 2,
        options: { text: 'ABC' },
    },
    {
        id: 2,
        type: 'game/textbox',
        next: null,
        options: { text: 'XYZ' },
    },
]
```

 I loop through the nodes of the graph. `id`, `type` and `options` are no problem. But when I'm at node with id 1 how can I get the ID of the node, that is connected to its output? In this example id 2.

I thought it has something todo with `outputs[0].links` but there is a `1`, not a `2`. So I guess it's something different :/

```js
const nodes = graph.serialize().nodes
const result = nodes.map(x => {
    console.log(x)
    return {
        id: x.id,
        type: x.type.replace(/game\//, ''),
        next: null, // @TODO How to get ID of the linked output?
        options: x.properties.nodeData,
    }
})
console.log(result)
```

Thanks in advance!

**Comment by jagenjo** [comment]
The ids you mention are the ids of the links, you can get the link like this:

```js
var link = graph.links[ link_id ];
```
and there you can find the node id:
```js
var node = graph.getNodeById( link.target_id );
```
