### ISSUE TITLE
Input / Property duality.  A quick check before I start coding.

### ISSUE THREAD

**Issue by benhar-dev** [jagenjo/litegraph.js#278]
Hi @jagenjo,

I just wanted to have a quick check with you.  I am going look at adding the ability to have a dual purpose "input port / property widget".  I have several nodes which benefit from having easy to fill in properties using your widget functionality.  But on occasion I would instead like to right click on the widget and say "convert to input port".  Also, for the same to apply in the reverse direction, by right clicking an input an selecting "convert to property".  As an example, on the image below I would like to have the option to make the "Rotation in degrees" an input if I need to provide the value programmatically.  

So, before I start my coding adventure I just wanted to check to see if you have something already in the background, or if this is something others have implemented.  

If not, then I'll make a start and will happily feed back on here how I get on. 

Again, fantastic work! :)

Ben  

![image](https://user-images.githubusercontent.com/53424421/144600915-22d929b7-659d-4468-ad3a-c48f8cc11b49.png)

**Comment by atlasan** [comment]
Hi @benhar-dev, this is very interesting and I wanted to do it myself.
I know there is `LGraphNode.prototype.getInputOrProperty` that gets the value of the connected slot, or if not present/connected, will than check for a property with that name. Just be careful with rename-enabled slots.
What I would do is to condition the widget to be hidden if the value is connected. Actually I would like to have a direct relation between a widget and the input slot, having both on the same Z, and hiding the slot name. The widget could show the actual data, and get disabled when the slot is connected.

**Comment by benhar-dev** [comment]
Hi @atlasan thank you for your feedback on this. 

This will be an open source visual component for TwinCAT HMI and TwinCAT Vision.  You are correct with your observation, this is very similar to OpenCV (based on many of the same functions) but for industrial controllers.  TwinCAT Vision It is currently programmed in structured text, but we are making a graphical front end in TwinCAT HMI just to help us try things out.  

I'm going to do a two staged attack on this.  First starting by implementing a getWidgetMenuOptions right click menu, which can then be used to support the "Convert to input".  We already have the getSlotMenuOptions which can be used to support the "Convert to property".  This, while utilizing the getInputOrProperty method you mentioned above, will allow a quick implementation of the feature we require.    

Once that is done then time permitting the idea about the input / widget slot would be something I'd like to look at too.

**Comment by mcejp** [comment]
In terms of UI, I would say that Blender really nails it.

![image](https://user-images.githubusercontent.com/29300939/154565357-7dfc0212-22bd-4c00-97c3-6101476e34e5.png)

**Comment by jagenjo** [comment]
yeah, but to add that feature it would be required a good refactor

**Comment by atlasan** [comment]
We could implement the logic during the node registration, checking for specific a property on the widgets (or on properties .. or slots ..) .. and take care of the mapping needed, similarly on how widget and properties can be actually tied.
But sure.. we need to take care of connected and disconnected events, and sure some other events and fixes.

**Comment by benhar-dev** [comment]
![PropertyInput](https://user-images.githubusercontent.com/53424421/166339235-0592916f-015c-486e-8cde-1fee9fab0774.gif)

Just incase you were interested to see what the current solution looks like.  We have made a number of modifications which allow us to add visible properties (properties with widgets) and if we pass in a data type then it automatically makes an input next to the widget.  This then hides / shows the widget when it is connected / disconnected.

**Comment by atlasan** [comment]
Hi @benhar-dev, this is it! Congrats. Did you implemented node types related to widgets types?
If you could sometime share it, many could appreciate it.
Cheers

**Comment by benhar-dev** [comment]
Thanks @atlasan, yes this should be possible.  We have a second repo to the main project which is dedicated to quickly testing the ui side of our project (95% litegraph).  I will make this available shortly and will post it here.  Also we are almost ready to open the full repo MIT open source so then all will be shared.  

We still use the litegraph.js behind the scenes, but this has been extended by wrapping much of the framework in to objects.  These objects then add the functionality.  

For example, 
![image](https://user-images.githubusercontent.com/53424421/166838488-673b6f6d-1b96-4d39-b3ed-d0b8031b9f7b.png)

**Comment by idle-code** [comment]
Sorry for reviving this old thread but Just for the followup - has this functionality landed into litegraph.js already?

**Comment by jagenjo** [comment]
no, it will require some big refactor, but is doable manually.

**Comment by idle-code** [comment]
@atlasan I came here because of ComfyUI - I haven't seen this feature there and I think it would be really welcome

**Comment by idle-code** [comment]
Yeah - it is there but it gets tiring after a while - @benhar-dev solution would be much better (at least that's my experience coming from Blender)

**Comment by iceboundflame** [comment]
@benhar-dev your solution looks great if it's available somewhere, I'm also interested in making such "connectable properties".

**Comment by benhar-dev** [comment]
Hi @iceboundflame, I can make it available for you. We are currently in the process of rewriting our app to a new version which will be for public release, but in the meantime I'll put the code in its own repo.  I'm not back on my computer until Monday so I'll add it then.

**Comment by clarkmcc** [comment]
Would also love to see a solution to this that is more along the blender lines.

**Comment by benhar-dev** [comment]
This is a small demo of the current implementation.  A few things to note.  We are converting the library to work as classes.  The current code does not work with the latest litegraph.  We are busy with the backend server coding at the moment.  Only once that is complete will we go back and update to the latest litegraph. 

https://github.com/benhar-dev/litegraph-port-property-duality

**Comment by clarkmcc** [comment]
@benhar-dev thanks for sharing. 

In the meantime, I spent the last few days full time pulling together a similar project heavily inspired by [threegn](https://github.com/roman01la/threegn) but rewritten from the ground up, and based on [xyflow](https://github.com/xyflow/xyflow) instead. There were other issues like [multiple outputs to single input](https://github.com/jagenjo/litegraph.js/issues/36) that are not supported in Litegraph and after several hours of trying just wasn't making sense with the amount of code changes I was making. 

So I ended up with this prototype, it's entirely declarative -- meaning you just specify all your data types, colors for the types, node types, what the inputs and outputs are and everything just works. You can also build your own node components and plug them in if the declarative approach isn't flexible enough. So far I've been able to express all my nodes as declarative components though.

I plan on open sourcing it soon once I've got the last few key objectives MVP'd into it. I'm primarily a backend guy so I'm still figuring out how to bundle and release a Javascript library but once that's up, maybe it will be useful for others that need a more Blender-style node graph editor.

https://github.com/jagenjo/litegraph.js/assets/6639685/6d7535ca-f1e6-484b-9e5d-28c5f7f8083a

```json5
{
  valueTypes: {
    string: {
      type: "string",
      name: "String",
      color: "#a1a1a1",
      inputType: "value",
      defaultValue: "",
    },
  },
  nodeGroups: {
    primitives: {
      type: "primitives",
      name: "Primitives",
      color: "#ef4444",
    },
  },
  nodes: {
    print: {
      type: "print",
      group: "primitives",
      name: "Print",
      inputs: [
        {
          name: "Value",
          identifier: "value",
          valueType: "string",
        },
      ]
    },
  },
}
```

**Comment by benhar-dev** [comment]
This looks very nice!

I completely agree with the declaring everything and letting the nodes create themselves.  This is part of the feature we are writing at the moment.  We actually use litegraph to draw the programs which are then activated on another piece of equipment (A plc running TwinCAT) we then pass the content back to litegraph to show what is going on. 

Originally this would involve writing two batches of nodes.  The front end nodes, (which litegraph would use to allow people to draw) and the back end nodes, which were the counterpart which run in the PLC. 

The new version now asks the backend to provide a blueprint for nodes, and litegraph makes them from blueprint and adds them to it's list of things that people can use. 

Hope to be fully releasing soon.  The repo is here, just in case you want to watch it to get notified when I do the push. 

[mobject-graph](https://graph.mobject.org/#/)
