### ISSUE TITLE
Add function to add comment section

### ISSUE THREAD

**Issue by gotwig** [jagenjo/litegraph.js#28]
there should be something like a node but without any functionality and only a title to comment whole zones: This zone does this, this zone does that, example:
https://blueprintue.com/blueprint/2ti4oh1s/

"Jump" is the title of the comment section

**Comment by jagenjo** [comment]
yes, I was thinking about decorations for the graph.
I will see how I can add it.

**Comment by jagenjo** [comment]
groups have been added
