### ISSUE TITLE
question

### ISSUE THREAD

**Issue by mofle07** [jagenjo/litegraph.js#286]
Can one input slot of one node be connected to output slots of multiple nodes?

**Comment by mofle07** [comment]
![Snipaste_2022-01-14_10-21-09](https://user-images.githubusercontent.com/42170476/149440539-7e54297b-9d9b-414d-99dd-ccebe047ed91.png)
just like the picture show

**Comment by jagenjo** [comment]
nop, not possible with the current architecture as getInputData will have to deal with mergin two connections data.
