### ISSUE TITLE
Add Cut/Copy/Paste functionality

### ISSUE THREAD

**Issue by gotwig** [jagenjo/litegraph.js#29]
Modern node editors allow to cut/copy/paste nodes to reuse existing nodes

**Comment by jagenjo** [comment]
That is totally supported, control+c and control+v, it even allow to copy several nodes and mantains the connections between them.

Check the latest version

**Comment by gotwig** [comment]
Im sorry for the two bug reports:
You are right the two features are in there, I just tried outdated versions (webgl sudio seems to also be outdated?)

**Comment by jagenjo** [comment]
yes, I will update it soon though
