### ISSUE TITLE
"Load" button does not show up on Image node

### ISSUE THREAD

**Issue by mcejp** [jagenjo/litegraph.js#291]
According to the source code, the node `graphics/image` should have a _Load_ button on it:

https://github.com/jagenjo/litegraph.js/blob/376f6434e87a04c309ed55620726f6e9b733c1a9/src/nodes/graphics.js#L85

However, when loading up the online demo, or `editor/index.html` from the repository, after adding an Image node this button is nowhere to be seen.

Is this a regression?

**Comment by jagenjo** [comment]
The Image nodes are totally deprecated and not maintained.
