### ISSUE TITLE
variables input and output from external code

### ISSUE THREAD

**Issue by culurciello** [jagenjo/litegraph.js#298]
Hi, I could not find information on how to input and output external code variables to and from litegraph. Wondering if there is an example or instructions.
Thank you for this great package and for the great work.

**Comment by jagenjo** [comment]
I totally discourage using eval, it is a safety problem as if one variable is called "while(1)" it will crash your browser.

Instead create nodes for every element, like a node for players, a node for levels, etc.

**Comment by culurciello** [comment]
thanks a lot Javi, will do!
