### ISSUE TITLE
how to compile it into an exe?

### ISSUE THREAD

**Issue by oldsheep0205** [jagenjo/litegraph.js#314]
I'm new in javascript, and hope to use this for json editing. In this case, I need to compile first. How to do that?

**Comment by atlasan** [comment]
To edit a json probably it's better to use some kind of editor, some text editor would have an utility for that, or try an html editor or an online one (eg. https://jsoneditoronline.org/)

**Comment by oldsheep0205** [comment]
> To edit a json probably it's better to use some kind of editor, some text editor would have an utility for that, or try an html editor or an online one (eg. https://jsoneditoronline.org/)
I'm writing game Mods which needs a connection between many jsons. In this case, common editor like notepad++ is not enough for me, that's why I want a visual editor lol

**Comment by oldsheep0205** [comment]
Another silly question, should I make a new project and copy everything in it? Since I cannnot run it now

**Comment by oldsheep0205** [comment]
I copied the first project code and made it as a html. But in VS I cannot run it, could u help me figure it out?
