### ISSUE TITLE
Display tooltip with node Description

### ISSUE THREAD

**Issue by elhakimz** [jagenjo/litegraph.js#333]
Hi Jagenjo,
I want to have this functionality: When a node is selected, it will display a tooltip with the content  of node.desc value , if it's unselected the tooltip will disappear

how can I achieve this ?

**Comment by elhakimz** [comment]
implemented
thanks !
![Untitled](https://user-images.githubusercontent.com/616176/216471010-749a7eb6-004b-4240-8757-369b73418b23.png)

**Comment by elhakimz** [comment]
@atlasan  , want to display charts  from chartjs in a node.., trying some techniques.. but failed to produce , always rendered start  from origin of the screen, not node's element

https://youtu.be/WjJdaDXN5Vs

**Comment by atlasan** [comment]
@elhakimz probably you just need to address the right element.
Take a look at the built-in plot node

**Comment by elhakimz** [comment]
@atlasan  , this newbie can make a linechart now
.
.
.
thanks ChatGPT  ..LOL
[](url)
![Untitled](https://user-images.githubusercontent.com/616176/216801522-b65a1468-cb68-41ae-a05f-30ee3aacd701.png)

`  function SimpleBarChart(){
         this.addInput("Data", "array");
         this.addOutput("Output", "array");
         this.properties = {
              color: "#3F51B5",
              width: 4,
          };
       }

        SimpleBarChart.prototype.onDrawBackground=function (ctx){

              if (this.flags.collapsed) {
                  return;
               }
                // Get the input values
                var values = this.getInputData(0)
                if(values==null) {
                   values=[]
                }

                // Get the maximum value in the input values
                var maxValue = Math.max(...values);

                // Calculate the bar width and height based on the node size
                var barWidth = (this.size[0] - (values.length - 1) * this.properties.width - 20) / values.length;
                var barHeight = this.size[1] - 20;

                // Set the color for the bars
                ctx.fillStyle = this.properties.color;

                // Draw the bars
                for (var i = 0; i < values.length; i++) {
                   ctx.fillStyle = this.properties.color;

                  var value = values[i];
                  var x = 10 + i * (barWidth + this.properties.width);

                  var y = barHeight - (value / maxValue * barHeight) + 10;
                   ctx.fillRect(x, y, barWidth, value / maxValue * barHeight);

                   ctx.fillStyle = "black";
                   ctx.font = "12px Arial";
                   ctx.textAlign = "center";
                   ctx.fillText(value, x + barWidth / 2, y - 5);
             }
        }


     SimpleBarChart.title = "Simple Bar Chart";
     SimpleBarChart.desc ="a simple bar chart of data"
     SimpleBarChart.size = [150,100];

     LiteGraph.registerNodeType("chart/simplebar", SimpleBarChart);`
