### ISSUE TITLE
`arrange` function never called ?

### ISSUE THREAD

**Issue by m957ymj75urz** [jagenjo/litegraph.js#339]
Hello,

I am wondering why the `LGraph.prototype.arrange` function defined L.1262 is never called anywhere ? The only mention is found L.12855 in the `LGraphCanvas.prototype.getCanvasMenuOptions` function but it's commented. 

Is this function deprecated or not stable enough ? 

Thanks

https://github.com/jagenjo/litegraph.js/blob/master/src/litegraph.js#L1262
https://github.com/jagenjo/litegraph.js/blob/master/src/litegraph.js#L12855

**Comment by jagenjo** [comment]
It was more like a test. It works although not much thought has been put into it. Feel free to use it.

**Comment by m957ymj75urz** [comment]
Thank you for the quick answer !
