### ISSUE TITLE
Resize doesnt work

### ISSUE THREAD

**Issue by gotwig** [jagenjo/litegraph.js#34]
The resize method (just like autoresize method) just make the canvas viewport larger and larger, those its inaccurate and doesnt stay on one new size:

Try to run it on the console in a div with fixed dimensions, everytime you run resize() on the graph canvas its getting only larger and larger, so it must be not accurate.

It even works in the demo.

**Comment by jagenjo** [comment]
Cannot replicate the error, tryed on http://tamats.com/projects/litegraph/demo/ calling graphcanvas.resize() and everything seems fine.

Be careful if you have other elements in the same parent.
