### ISSUE TITLE
Unit tests

### ISSUE THREAD

**Issue by moritz89** [jagenjo/litegraph.js#341]
Has there been a discussion on adding/having/using unit tests and what are the views of the maintainers on this aspect?

**Comment by jagenjo** [comment]
Not sure how to do unit tests as everything is very visual, besides some generic functions.

**Comment by moritz89** [comment]
You're right there that it would be limited in scope

**Comment by atlasan** [comment]
Actually one could setup a test making basic things:
- create a node
- update some parameter
- create another
- create connection
- update connection
- remove connection
A cycle for creating and doing the same for every node type could be useful too.
There could be test graphs that once loaded and run should eg. return a known value in a variable.

Saing so I'm not really used at using tests myself. Should learn better ^_^

**Comment by atlasan** [comment]
You are right Javi.
Those test would have been helpful indeed while I was refactoring the event-based part and the refactoring did for the auto-connect improvement.
So @moritz89 if you eventually do something it could would be nice to have.

**Comment by atlasan** [comment]
Actually there is a functionality implemented that already spawn every node at first run to get node list based on inputs and oitputs types. That's for proposing node creation and filtering nodes in the search menu.
Some errors in random nodes had already come out that way.

**Comment by paireks** [comment]
Just for the record, what I do to unit-test single components in Grasshopper: https://www.youtube.com/watch?v=0j-O9V5DX9s
So later I have 1 giant definition with all components I test and 1 report for all of them.
So after an update I open this one giant defintion and check if everything pass.
But it works well only for components that have inputs and outputs.
