### ISSUE TITLE
Can I execute configuration files offline?

### ISSUE THREAD

**Issue by sonlia** [jagenjo/litegraph.js#344]
Node program can be executed offline

**Comment by jagenjo** [comment]
what do you mean offline? outside of the browser? well, you will need to create a nodejs app that runs it, it should be fairly simple.

**Comment by sonlia** [comment]
Just some ideas for us to explore, you to assess the feasibility, I said offline operation, there are two ways: 
the first one. For example, there is a simple requirement, we concatenate the strings through nodes, which can be used as a tool for me, I can load the project file anywhere, and I can run, for example, LGraph.config("config.json") run("arg"), just like the vfx nuke software can cmd to run the project. 
In the second method, you can generate the corresponding code and then execute it. The main goal is to generate code. Because the connection of nodes is very similar to that of an ast tree, is it possible to connect nodes and then generate an ast tree?

**Comment by jagenjo** [comment]
LiteGraph nodes dont output code, but you can create your own set of nodes that do.
I did it for shader code generation.

**Comment by sonlia** [comment]
thanks
