### ISSUE TITLE
How to empty the default node？

### ISSUE THREAD

**Issue by sonlia** [jagenjo/litegraph.js#346]
Hi friend, the system has many default nodes, I want to only show custom nodes, so I use, clearRegisteredTypes, clear all nodes, and then re-register my own nodes, but there is a problem, one question is: the search box is missing, and an error is reported, 
/litegraph.js:11172 Uncaught ReferenceError: def_options is not defined
    at LGraphCanvas.showSearchBox (litegraph.js:11172:9)
    at LGraphCanvas.processMouseDown (litegraph.js:6113:12)
the second problem is that the subgraph does not work, and when I drag out the input node in the subgraph, an error is reported 
litegraph.js:7989 graph input node not found: graph/input

dbclick subgraph node error is reported
litegraph.js:12293 Uncaught ReferenceError: panel is not defined
    at LGraphCanvas.showShowNodePanel (litegraph.js:12293:3)
    at LGraphCanvas.processNodeDblClicked (litegraph.js:7282:9)
    at LGraphCanvas.processMouseDown (litegraph.js:6036:30)

**Comment by jagenjo** [comment]
subgraph is one of the nodes you removed, you will have to add it again.

the dblclick has been fixed today.

the def_options no idea, will check. If you want to do a PR with a fix I will be happy.

**Comment by sonlia** [comment]
thans

**Comment by sonlia** [comment]
> this fix part of 0.7.12 ? because im still facing this issue locally here

Subgraph  need    GraphOutput, GraphInput  you need import it
