### ISSUE TITLE
Questions about API usage

### ISSUE THREAD

**Issue by baldurg** [jagenjo/litegraph.js#351]
Hello, I am working on implementing a UI for an existing audio mixer/filter that is managed via a HTTP API. I have been reading through all of the documentation I can find but it is not very verbose, and I don't do Javascript development every day, my every day is C/C++.

First question is, can I somehow allow a single input to have multiple connections, as the underlying mixer application allows this in its modules, or can I dynamically create more input ports on the node in the callback on connection?

Second question, what is the recommended method to pass data through to the registered callbacks when I'm using the same callback function to manage multiple types of nodes, and multiple separate instances of the nodes?
Like, when I create a node, what is the best way to store data related to that instance that can be accessed by all the other callbacks that are called by that node?

**Comment by baldurg** [comment]
Thank you.
Another thing, can I add a node without making it visible in the right click library? As my application involves a handful of nodes that represent physical ports on the mixer and thus cannot be added or removed by the user.

**Comment by jagenjo** [comment]
not sure now, but that should be easy to implement.
