### ISSUE TITLE
How does one set the LiteGraph layout to be vertical?

### ISSUE THREAD

**Issue by dangerstudios** [jagenjo/litegraph.js#368]
Awesome ui!!!

I saw a commit for it but having trouble getting it to work?

```
// Set the layout to be vertical
        graph.layout = LiteGraph.VERTICAL_LAYOUT;
```
(this doesn't work obviously)

**Comment by moritz89** [comment]
Have a look at the `LGraph.prototype.arrange` function. Vertical layout probably works, but might need to be checked / tests written for it.

**Comment by dangerstudios** [comment]
hmmm, no I think that function just arranges the nodes into a tidy layout? at least that's all it seems to do when I call it.

I was wondering how this was achieved(image from the github index page)?
![image](https://user-images.githubusercontent.com/63320852/230881206-57c36481-a7d4-4ce3-9dea-00ba51d89630.png)

**Comment by atlasan** [comment]
![image](https://user-images.githubusercontent.com/15611089/230894185-cbfba1bd-1cca-48d8-bad8-f7ae06433b20.png)

[	this.horizontal = true;](https://github.com/jagenjo/litegraph.js/blob/9be2c84205f98f2a0deeda8b656d2a2e16433cac/editor/js/demos.js#L195)

**Comment by dangerstudios** [comment]
awesome!!
