### ISSUE TITLE
cube rotation with litegraph and three.js

### ISSUE THREAD

**Issue by MMrofficial** [jagenjo/litegraph.js#37]
Hi
I've written a rotation function
How can I rotate the cube with this node?

**Comment by jagenjo** [comment]
you will need some sort of port of three.js to litegraph to work.
there are matrix and quaternion rotation functions but they do not work with threejs directly, you need to convert them manually. Integrating litegraph and threejs is not so simple.

**Comment by NothersInGame** [comment]
Im working at that... Maybe when i end you can download it ;)
