### ISSUE TITLE
Shake node to break connections! ( hey it's worth a try :) )

### ISSUE THREAD

**Issue by dangerstudios** [jagenjo/litegraph.js#375]
Shake node to break connections, would this be possible?

**Comment by dangerstudios** [comment]
yeah! even just dragging a node over a connected noodle to insert that node in the chain would be amazing :)

**Comment by atlasan** [comment]
there should be already implemented the add node in between: click on the link middle point and choose add

**Comment by dangerstudios** [comment]
yeah that totally works, but as a UX thing it would be really nice to be able drag a lonely node over a noodle to connect it, and then shake to disconnect. For example; if you are smashing a bunch of math nodes together or re-arranging a bunch of nodes etc.

**Comment by jagenjo** [comment]
I hate autoconnections, I suffer them a lot in Blender when dragging stuff around. Shaking... not sure, will think about i t.

**Comment by dangerstudios** [comment]
ah damn, I'm so used to these features coming from houdini & nuke and dealing with tons of nodes

![Animation](https://user-images.githubusercontent.com/63320852/231106759-a06efbb3-4a25-4e97-ab89-9aec5379333b.gif)

**Comment by atlasan** [comment]
This would be a feature, like the others, enabled or disabled or customized, it surely not need to be the default.
When working with nodes some feature can be a time and click saver (I tell this while suffering from a tendon inflammation after a 2months node clicking project)
