### ISSUE TITLE
connect doesn't work after calling configure() on empty graph

### ISSUE THREAD

**Issue by coderofsalvation** [jagenjo/litegraph.js#38]
Hi,

I can succesfully export the graph using `serialize()`, however it doesn't draw the connections PLUS it doesn't allow any (event) connections anymore AFTER loading the result of `serialize()` using `configure()`:

![recording](https://user-images.githubusercontent.com/180068/40670707-366b042a-636a-11e8-97dc-f4a61e2756c3.gif)

Ever seen this before / any advice?
I'm not getting any errors in the errorconsole (turning on LiteGraph's debug flag doesn't provide more info either)

Leon

**Comment by jagenjo** [comment]
it seems like it is already connected by the link doesnt show.
Is it online? can I see it?

Are you using the latest version? I fixed an error related to that some time ago.

**Comment by jagenjo** [comment]
Im not sure but I think I fixed this error solving other problems so Im gonna close this issue.
