### ISSUE TITLE
Multiline Text Node live update

### ISSUE THREAD

**Issue by rt974** [jagenjo/litegraph.js#382]
Hi,

i looked at various examples, in the editor. I still dont understand how this works, there is no documentation on how to customize nodes.
I need a bunch of nodes that display multiline texts such as the widget/text demo, and gets updated whenever some event happens to its inputs, i need to see the text directly displayed in the node body as that widget does. unfortunately i have no idea what corresponds to what, the widget got so many properties i have no idea which controls the actual text that is displayed, and how to update it when inputs change.

2) Also it seems like this runs in realtime, is there any way to execute the graph without it looping forever as a game engine.

Thanks in advance for your help. If someone can clarify these things or point me to some documentation/manual.

**Comment by rt974** [comment]
Alright i got it working. i also fixed the resizing when updating text :


`function Textarea()
{
	this.addOutput("string", "string");
	this.addProperty("value", "dfdddddd");
	this.widget = this.addWidget("textarea","value","","value");  //link to property value
	this.widgets_up = true;
	this.size = [180, 200];
	
	this.properties = {
		value: "fdfdfddf",
		font: "Arial",
		fontsize: 8,
		color: "#AAA",
		align: "left",
		glowSize: 0,
		decimals: 1
	};
}


Textarea.title = "Klona Textarea";
Textarea.desc = "Klona Textarea Desc";


Textarea.prototype.onPropertyChanged = function(name, value) {
        this.properties[name] = value;
        this.str = typeof value == "number" ? value.toFixed(3) : value;
        
		
		//this.resize();
		
		
		var lines = this.properties["value"].split("\n");
		var nb_lines = lines.length;
		
		console.log("nb_lines " + nb_lines + " " + this.properties["value"])
		
		this.size[1] = 10 + nb_lines * 10;
		
		//this.size = [180, 300];
		this.setDirtyCanvas(true);
		
        return true;
    };

Textarea.prototype.onDrawForeground = function(ctx) {
        //ctx.fillStyle="#000";
        //ctx.fillRect(0,0,100,60);
        ctx.fillStyle = this.properties["color"];
        var v = this.properties["value"];

        if (this.properties["glowSize"]) {
            ctx.shadowColor = this.properties.color;
            ctx.shadowOffsetX = 0;
            ctx.shadowOffsetY = 0;
            ctx.shadowBlur = this.properties["glowSize"];
        } else {
            ctx.shadowColor = "transparent";
        }

        var fontsize = this.properties["fontsize"];

        ctx.textAlign = this.properties["align"];
        ctx.font = fontsize.toString() + "px " + this.properties["font"];
        this.str =
            typeof v == "number" ? v.toFixed(this.properties["decimals"]) : v;

        if (typeof this.str == "string") {
            var lines = this.str.replace(/[\r\n]/g, "\\n").split("\\n");
            for (var i=0; i < lines.length; i++) {
                ctx.fillText(
                    lines[i],
                    this.properties["align"] == "left" ? 15 : this.size[0] - 15,
                    fontsize * -0.15 + fontsize * (parseInt(i) + 1)
                );
            }
        }
}

Textarea.prototype.onExecute = function() {
	
	//attribute proper output, it seems that internally an execute socket is set to channel 0, when connected
	//this.setOutputData(0, this.properties["value"]);
	this.setOutputData(1, this.properties["value"]);
};

Textarea.prototype.getTitle = function() {
        if (this.flags.collapsed) {
            return this.properties.value;
        }
        return this.title;
    };

Textarea.prototype.setValue = function(v)
{
	this.setProperty("value",v);
}

Textarea.prototype.onDropFile = function(file)
{
	var that = this;
	var reader = new FileReader();
	reader.onload = function(e)
	{
		that.setProperty("value",e.target.result);
	}
	reader.readAsText(file);
}

LiteGraph.registerNodeType("Klona/Textarea", Textarea);`

**Comment by moritz89** [comment]
Looks like a valid bug. Just tested your code, but it also doesn't seem to resize the node correctly either. Am I missing something?

![image](https://user-images.githubusercontent.com/1592994/232449661-38de3bc8-00c1-4bbb-a6c9-c3bb4315dfa5.png)
