### ISSUE TITLE
What is the best approach to make all nodes execute only when parent nodes complete execution? 

### ISSUE THREAD

**Issue by SMUsamaShah** [jagenjo/litegraph.js#398]
I was trying to use litegraph as a frontend of a webapp where a node's output is fed to next one only after receiving response. Currently all nodes run onExecute all at the same time irrespective of their dependencies. 

To get around this for web requests i made a few custom nodes with events but later realized that if I want to use any of the built in nodes I have to modify them. This means I have to modify all the nodes to also accept event triggers so that I can use them in my workflow. 

Is there a shorter way? Is there any thing else I can change in litegraph such that a node only execute after all previous nodes have completed their execution?

**Comment by jagenjo** [comment]
I didnt know about that LiteGraph.do_add_triggers_slots @atlasan, it seems a cool idea. Who did it?

**Comment by SMUsamaShah** [comment]
@atlasan This is exactly what I was looking for. Thank you very much.

**Comment by jagenjo** [comment]
I just want to add that the onTrigger was more of an experiment. The right way should be to create nodes that use events.
