### ISSUE TITLE
Documentation Error in LGraph.prototype.configure

### ISSUE THREAD

**Issue by cjimison** [jagenjo/litegraph.js#404]
The documentation says this that "data" payload should be a JSON string value but it looks like it should be in the object format returned from the `serialize` call.

I think this is might just be an overlooked refactor.  Happy to create a PR but wanted to submit an issue first just in case I am misunderstanding how this should work:

Code:

```
    /**
     * Configure a graph from a JSON string
     * @method configure
     * @param {String} str configure a graph from a JSON string
     * @param {Boolean} returns if there was any error parsing
     */
    LGraph.prototype.configure = function(data, keep_old) {
 ```
 
Test code to run in a console/etc:
 
 ```
// Assuming that the variable `graph` points to an LGraph instance

// Export your data 
let dataRaw = graph.serialize();
let dataStr = JSON.stringify(dataRaw );

// clear the current graph.
graph.clear();

// Now import that old data
graph.configure(dataStr , false);

// Nothing shows up 

// Import the "object" version
graph.configure(dataRaw , false);

// you should now see your old graph
 ```
 
If my example is correct I will happily create a PR and submit it, but if I am using this incorrectly and someone could point me to some docs/code/etc I would most appreciative.
  
Thanks!

**Comment by jagenjo** [comment]
yeah, send the PR and I will accept it.
