### ISSUE TITLE
slider widget precision is hardcoded?

### ISSUE THREAD

**Issue by Guillaume-Fgt** [jagenjo/litegraph.js#409]
Hi, I would like to use a slider widget type to select an integer value. I tried to add a property `"precision":0` but I still have 3 digits precision. Looking at the code, I think the value is hardcoded in `/src)/litegraph.js`:

```js
  ctx.fillText(
      w.label || w.name + "  " + Number(w.value).toFixed(3),
      widget_width * 0.5,
      y + H * 0.7
  );
```
```js
  function toFixed(a) {
      if (a != null && a.constructor === Number) {
          return a.toFixed(this.properties.precision);
      }
      return a;
  }
```

Do you confirm it is the case? Is it possible to update the code to take the precision into account?

**Comment by jagenjo** [comment]
yeah, send a PR, but remember that precision could be undefined, so control that case.

```Number(w.value).toFixed( this.properties.precision == null ? 3 : this.properties.precision),
```
