### ISSUE TITLE
MathOperations are always addition with initial properties

### ISSUE THREAD

**Issue by zbarbuto** [jagenjo/litegraph.js#419]
Starting with a basic setup of (`A=1` `B=3`) -> `MAX` -> `watch` - the numbers are actually added together and we get `4`

<img width="553" alt="image" src="https://github.com/jagenjo/litegraph.js/assets/9100419/9c484960-cce0-4192-bed8-75e87099c5dd">

If we manually change the OP to `min`, we get the expected value of `1`
<img width="939" alt="image" src="https://github.com/jagenjo/litegraph.js/assets/9100419/5fd69fdd-4ddf-4c87-9290-318ececb215a">

Then manually changing back to `max` we get the corrected max value of `3`
<img width="946" alt="image" src="https://github.com/jagenjo/litegraph.js/assets/9100419/c04f2ee3-ca5c-46ba-82b6-bc607c3cd342">

This applies to all of the basic math nodes, such as `*` or `-` - the initial output is always addition (examples shown are both fresh graphs without manually changing the `OP` property):

![image](https://github.com/jagenjo/litegraph.js/assets/9100419/24f6bfba-1534-42ca-ad5f-f2b2d7577ddf)

![image](https://github.com/jagenjo/litegraph.js/assets/9100419/f0221f7f-d759-442b-8a9c-b4f1d184fefb)

Playing around with some breakpoints in the example project, it seems that since the operation's `_func` is not set until `MathOperation.prototype.onPropertyChanged` is called, the default `_func` of `MathOperation` (which is `return A + B`) is used even though the node added was a `MIN`/`MAX` node.

**Comment by jagenjo** [comment]
yep, fixed, I did a push
