### ISSUE TITLE
Is there an ability to group nodes?

### ISSUE THREAD

**Issue by bachirelkhoury** [jagenjo/litegraph.js#42]
Is it possible to group nodes so they can be moved together and collapse etc...?
![screen shot 2018-08-29 at 1 47 02 pm](https://user-images.githubusercontent.com/186698/44764256-263e6b80-ab92-11e8-9132-5755e64e982f.png)

**Comment by jagenjo** [comment]
Yes and no, LiteGraph supports subgraphs, but you have to create manually and it is still a little bit buggy.
Check creating a subgraph node.
