### ISSUE TITLE
Maybe it is an issue

### ISSUE THREAD

**Issue by byte911** [jagenjo/litegraph.js#424]
![image](https://github.com/jagenjo/litegraph.js/assets/92360792/5e5024a0-572e-4c06-9006-3a2c5518b104)

I think it's an issue, then I will view code to verify it.

**Comment by jagenjo** [comment]
is the graph running? if it is not running the data is not being feed to the branch node.

**Comment by jagenjo** [comment]
yes, thats a huge problem currently. Not sure how to handle it. The only solution I can think of is to execute the whole graph once an event is triggered, but that would be slow. The optiomal solution implies some analysis of the graph to see which nodes are affected by the event and execute only those.

**Comment by byte911** [comment]
@atlasan @jagenjo thanks, I got it.
