### ISSUE TITLE
String

### ISSUE THREAD

**Issue by NothersInGame** [jagenjo/litegraph.js#43]
Hola jagenjo, me impresiona tu trabajo pero tengo una duda, yo tambien ando creando un Motor y le quiero implementar tambien unas "blueprints" pero llego un punto al que necesito un input de texto pero que de un output, como puedo hacer eso??

**Comment by jagenjo** [comment]
Te refieres a un nodo que permita escribir? Ahora no hay ninguno pero lo mejor seria programarte uno que si haces doble click lance la funcion prompt de js

**Comment by NothersInGame** [comment]
Ah claro!. Muchas gracias, excelente librería.

**Comment by NothersInGame** [comment]
O también podremos modificar el text que de un output.
