### ISSUE TITLE
Update/Modify widget options

### ISSUE THREAD

**Issue by Levaru** [jagenjo/litegraph.js#432]
I have a node with the standard number widget. According to the documentation, it is possible to provide options to that number widget (min, max, step, precision).

Is there a way to modify those options after the widget was created? I tried setting it directly via `this.widget.options = my_options` but this had no effect.

**Comment by Levaru** [comment]
I found a workaround after looking at the source code: 

`this.widgets[0].options = my_options` 

Right now this is enough for me but it would be great if there was an additional function like `setProperty`. Maybe something like `setWidgetOptions(widget_index, options)` or `setWidgetOptions(widget_index, option_name, value)`?

**Comment by jagenjo** [comment]
it is just a regular JS object holding all the options, accessing it directly makes more sense.
