### ISSUE TITLE
Feature Request: Flip I/O

### ISSUE THREAD

**Issue by Immac** [jagenjo/litegraph.js#435]
Being able to flip a node I/O.
Adding a property flip_io that can be toggled per individual node so workflows can be done towards any direction and not just left to right/ up to down.  
Mostly clarity increase change. (Just take into account in simple cases like this the clarity improvements are not so obvious)
![image](https://github.com/jagenjo/litegraph.js/assets/3265190/e83a6a07-7c35-46f8-bc9a-5f098a2f9032)
vs
![image](https://github.com/jagenjo/litegraph.js/assets/3265190/1f7a219b-5c71-4139-8371-13df0fe17c51)

**Comment by jagenjo** [comment]
reversing the flow would be very confusing to the readability of the graph, and imply lots of conditioning in the system so it is not a valid feature.
