### ISSUE TITLE
Error JSON

### ISSUE THREAD

**Issue by NothersInGame** [jagenjo/litegraph.js#44]
Hola. Me gustaria saber como hacer para obtener un JSON del metodo serialize, pues intente con toString, hice que escribiera en consola y lo unico que hace es poner [object Object] lo mismo hice pasa cuando guardo una variable con el metodo serialize e intento ponerlo en JSON me pone lo mismo... PS:Uso JSON.stringify

**Comment by jagenjo** [comment]
basta con llamar JSON.stringify( graph.serialize() ) para obtener un string con los datos.
el toString no sirve para estos casos
