### ISSUE TITLE
node.getInputNode(0) returns null when a connection exists

### ISSUE THREAD

**Issue by tanevanwifferen** [jagenjo/litegraph.js#46]
The first link in the chart is made with id = 0. The link id is stored in the node input, which is 0. When I call getInputNode(0), there is some code:

```
if(!input || !input.link)
		return null;
```
The second case `!input.link` evaluates to !0, which evaluates to true.

Solution: 

change the id of the first link to 1, or change the code to

```
if(!input)
    return null;
if(input.link == null)
    return null;
```

**Comment by jagenjo** [comment]
You are correct, I set the first id to 1 and also check that input.link === null to avoid that error.
It has been uploaded.

Cheers
