### ISSUE TITLE
How do I change the color of a slot?

### ISSUE THREAD

**Issue by LeMoussel** [jagenjo/litegraph.js#478]
I do this test node 
```javascript
class CustomConstSpecialNumber {
	constructor() {
		this.title = "Const Special";
		this.desc = "Constant special";
		this.color = '#222234'
                this.bgcolor = '#333257'
		this.addOutput("value", "special", {color: "#DDDD"});
		this.addProperty("value", 1.0);
	}
	onExecute() {
		this.setOutputData(0, this.properties["value"]);
	}
}
```
but the output slot color is always green.
![image](https://github.com/jagenjo/litegraph.js/assets/1816573/c00593b3-2c16-4edf-a430-221e9ec82362)

Is it possible to change the color of the slot? If yes, how?

**Comment by atlasan** [comment]
There are two array properties _default_connection_color_byTypeOff_ and _default_connection_color_byType_ on LGraphCanvas
Something like this should work:
```
LGraphCanvas.default_connection_color_byTypeOff = {
            number: "#474",
            string: "#447",
            boolean: "#744",
            special: "#FFF",
};
LGraphCanvas.default_connection_color_byType = {
            number: "#7F7",
            string: "#77F",
            boolean: "#F77",
            special: "#DDD",
 }
```

**Comment by LeMoussel** [comment]
Thanks for your help.
It's Ok. I use [default_connection_color_byType ](https://github.com/jagenjo/litegraph.js/blob/master/build/litegraph.js#L8676).
I couldn't find anything about this in the documentation.

**Comment by atlasan** [comment]
You're right, I'm better at adding functionalities than improving documentation ^_^
But I would add for sure the color slot in the options ( .. maybe not in the documentation :p )
