### ISSUE TITLE
Settings and options related to Litegraph and Canvas 

### ISSUE THREAD

**Issue by breadam** [jagenjo/litegraph.js#494]
Hey there, 

Is there anyting missing? And are there any embedded options that is impossible to configure?

Thank you,

`export const CANVAS_SETTINGS = {
  round_radius: 4,
  allow_dragcanvas: true,
  allow_dragnodes: true,
  allow_interaction: true,
  allow_reconnect_links: true,
  multi_select: true,
  allow_searchbox: false,
  always_render_background: true,
  connections_width: 3,
  /*default_connection_color: {
    input_off: '#fff';
    input_on: '#fff';
    output_off: '#fff';
    output_on: '#fff';
  },
  default_link_color: '#fff',
  inner_text_font: 'Montserrat',
  node_title_color: '#fff',
  render_canvas_border:true;
  render_collapsed_slots:true;
  render_connection_arrows:true;
  render_connections_border:true;
  render_connections_shadows:true;
  render_curved_connections:true;
  render_execution_order:true;
  render_only_selected:true;
  render_shadows:true;
  render_title_colored:true;
  round_radius:true;
  show_info:true;
  title_text_font:'Montserrat';
  use_gradients:true;
  zoom_modify_alpha:true;
  highquality_render:true;
  
  */
};

export const CANVAS_OPTIONS = {
  show_info: false,
  autoresize: false,
  render_shadows: false,
};

export const LITEGRAPH_OPTIONS = {
  search_show_all_on_open: false,
  debug: true,
  search_filter_enabled: false,
  CANVAS_GRID_SIZE: 20,

  NODE_TITLE_HEIGHT: 30,
  NODE_TITLE_TEXT_Y: 20,
  NODE_SLOT_HEIGHT: 20,
  NODE_WIDGET_HEIGHT: 20,
  NODE_WIDTH: 140,
  NODE_MIN_WIDTH: 50,
  NODE_COLLAPSED_RADIUS: 10,
  NODE_COLLAPSED_WIDTH: 80,
  NODE_TITLE_COLOR: "#999",
  NODE_SELECTED_TITLE_COLOR: "#FFF",
  NODE_TEXT_SIZE: 14,
  NODE_TEXT_COLOR: "#AAA",
  NODE_SUBTEXT_SIZE: 12,
  NODE_DEFAULT_COLOR: "#333",
  NODE_DEFAULT_BGCOLOR: "#353535",
  NODE_DEFAULT_BOXCOLOR: "#666",
  NODE_DEFAULT_SHAPE: "box",
  NODE_BOX_OUTLINE_COLOR: "#f00",
  DEFAULT_SHADOW_COLOR: "rgba(0,0,0,0.5)",
  DEFAULT_GROUP_FONT: 24,

  WIDGET_BGCOLOR: "#222",
  WIDGET_OUTLINE_COLOR: "#666",
  WIDGET_TEXT_COLOR: "#DDD",
  WIDGET_SECONDARY_TEXT_COLOR: "#999",

  LINK_COLOR: "#9A9",
  EVENT_LINK_COLOR: "#A86",
  CONNECTING_LINK_COLOR: "#AFA",

  MAX_NUMBER_OF_NODES: 1000,
  DEFAULT_POSITION: [100, 100],
  VALID_SHAPES: ["default", "box", "round", "card"], //,"circle"

  NODE_MODES_COLORS: ["#666", "#422", "#333", "#224", "#626"],
};
`

**Comment by atlasan** [comment]
Hi!
You are correct and your list seems good, some variable could be missing and some others are hard coded. Atm the way is to direct assign those as there is no method do that in bulk. An initial exposing of those was in the demo editor.
https://github.com/jagenjo/litegraph.js/blob/master/editor/js/defaults.js

**Comment by breadam** [comment]
I'll check it out. Thank you!:)

Ps: I'm just using Object.assign(....) for the settings
