### ISSUE TITLE
"This browser doesn't support Canvas" on Chrome 61

### ISSUE THREAD

**Issue by crener** [jagenjo/litegraph.js#5]
Running the example code from the index.html produces an error in chrome. I know that this should work on the latest chrome since the demo code runs just fine. So the example should work too...

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Lite Graph Editor</title>
</head>
<body>
<div id="editor"></div>

<script type="text/javascript" src="litegraph.js"></script>
<script>
    var graph = new LGraph();
    var canvas = new LGraphCanvas("#editor");

    var node_const = LiteGraph.createNode("basic/const");
    node_const.pos = [200, 200];
    graph.add(node_const);
    node_const.setValue(4.5);

    var node_watch = LiteGraph.createNode("basic/watch");
    node_watch.pos = [700, 200];
    graph.add(node_watch);

    graph.start();
</script>
</body>
</html>
```

Chrome version 61

**Comment by jagenjo** [comment]
Strange, I'm not getting the error. Can you tell me which error do you get?

**Comment by crener** [comment]
"Uncaught This browser doesnt support Canvas" -litegraph.js:2725
thats with the lite graph file from src.

If you copy the liteGraph.js and the html from above, save it in a directory and open the html in chrome you get the above.

**Comment by jagenjo** [comment]
the "editor" element in your HTML is not a canvas, thats why it doesnt work. change it like this:

<canvas id="editor" width=800 height=600></canvas>

**Comment by crener** [comment]
Hmm, fair enough. I just figured since the demo code.js creates the editor via the `var editor = new LiteGraph.Editor("main");` line. I shouldn't have presumed that the editor without the top bar worked the same way.

Thanks

**Comment by jagenjo** [comment]
Yes, is a little bit confusing, I added an error if the element is not a canvas explaining it.

In the future maybe I will add the option of create the canvas and attached to the element.
