### ISSUE TITLE
Add nodes question 

### ISSUE THREAD

**Issue by threethreenine** [jagenjo/litegraph.js#52]
I want to know how I can use the right mouse button to open the menu that creates the node in the visual editor.
I tried to do this, but nothing happened.
`document.getElementById("Graph_Edit").addEventListener("mousedown",eventHandler,false);
function eventHandler(event) {
    graphCanvas.processMouseDown(event);  
}
`
I saw your Demo, in which i can right click to create or delete a node.
Thank you very much for helping me solve this problem.

**Comment by jagenjo** [comment]
you do not have to do anything, it is automatic. when you create a LGraphCanvas and pass a canvas, it calls the method bindEvents that bind the mouse events. how are you creating the graphcanvas?

**Comment by threethreenine** [comment]
我想我是我没有绑定 litegraph.css 脚本。

**Comment by threethreenine** [comment]
I think I didn't bind the litegraph.css script.

**Comment by threethreenine** [comment]
I think I didn't bind the litegraph.css.

**Comment by threethreenine** [comment]
I have a new problem. The Add Node panel does not appear in the graph, but is pushed out of the page by my div.

**Comment by threethreenine** [comment]
In the  function "ContextMenu" , I found that after right-clicking, the value of top becomes -56 after this code.
`		// if(top > (body_rect.height - root_rect.height - 10))
		// 	top = (body_rect.height - root_rect.height - 10);`
I commented on this code and my problem was solved.

**Comment by threethreenine** [comment]
In the function "ContextMenu" , I found that after right-clicking, the value of top becomes -56 after this code.
'// if(top > (body_rect.height - root_rect.height - 10)) '
'// top = (body_rect.height - root_rect.height - 10);'
I commented on this code and my problem was solved.

**Comment by threethreenine** [comment]
In the function "ContextMenu" , I found that after right-clicking, the value of top becomes -56 after this code.
`// if(top > (body_rect.height - root_rect.height - 10)) `
`// top = (body_rect.height - root_rect.height - 10);`
I commented on this code and my problem was solved.

**Comment by jagenjo** [comment]
sounds to be that there is a problem with how you include the CSS
