### ISSUE TITLE
ondbClick listener on LiteGraphNode and remove already present registerNodeType

### ISSUE THREAD

**Issue by nixar0x0** [jagenjo/litegraph.js#6]
How can I add event listener on LiteGraphNode ? And can you also tell how to remove register node types

**Comment by celllaw** [comment]
Mentioned in Documentation
	supported callbacks: 
		+ onAdded: when added to graph
		+ onRemoved: when removed from graph
		+ onStart:	when the graph starts playing
		+ onStop:	when the graph stops playing
		+ onDrawForeground: render the inside widgets inside the node
		+ onDrawBackground: render the background area inside the node (only in edit mode)
		+ onMouseDown
		+ onMouseMove
		+ onMouseUp
		+ onMouseEnter
		+ onMouseLeave
		+ onExecute: execute the node
		+ onPropertyChanged: when a property is changed in the panel (return true to skip default behaviour)
		+ onGetInputs: returns an array of possible inputs
		+ onGetOutputs: returns an array of possible outputs
		+ onDblClick
		+ onSerialize
		+ onSelected
		+ onDeselected
		+ onDropItem : DOM item dropped over the node
		+ onDropFile : file dropped over the node
		+ onConnectInput : if returns false the incoming connection will be canceled
		+ onConnectionsChange : a connection changed (new one or removed) (LiteGraph.INPUT or LiteGraph.OUTPUT, slot, true if connected, link_info, input_info )

**Comment by jagenjo** [comment]
you create that method in your node class.

**Comment by celllaw** [comment]
can you please show me snippet

**Comment by celllaw** [comment]
How can I have the  multiple connection in one slot ??

**Comment by jagenjo** [comment]
to add multiple options, separate the name with bars, like "pores/foo/faa"

multiple connections are only supported in the output, not the input.
