### ISSUE TITLE
features.json : how to recreate these sliders/controls etc in one node?

### ISSUE THREAD

**Issue by coderofsalvation** [jagenjo/litegraph.js#61]
![screenshot 2019-01-02 at 03 24 33](https://user-images.githubusercontent.com/180068/50578734-07046300-0e3e-11e9-873a-f2507996bbba.png)

**Comment by jagenjo** [comment]
using the UI, when ready I just type in the console  ```copy( JSON.stringify( graph.serialize() ) )``` and paste it in the file.

**Comment by coderofsalvation** [comment]
ah thanks, i will look into that. Thx for pointing out (and happy NY from Budapest/Hungary btw!)

**Comment by coderofsalvation** [comment]
ah i get it. It was just a programmaticaly registered node.
Didn't know about the `.addWidget()`-function, thx very handy!

**Comment by jagenjo** [comment]
[https://github.com/jagenjo/litegraph.js/blob/master/guides/README.md#node-widgets](I have added a small guide here)
