### ISSUE TITLE
Exemple code in README.md doesn't work

### ISSUE THREAD

**Issue by mosleymos** [jagenjo/litegraph.js#64]
First, sorry for my english, but it's not my natural tongue, and I'm pretty bad at writing it.
I tried your code example in the README and it doesn't work. 
I think the bug come from this instruction
```javascript
node_const.setValue(4.5); 
```
The second problem come from the popup navigation that appears at the bottom of the page
I can't add a simple basic node.

I've tried on chromium

Chromium | 70.0.3538.77 (Build officiel) Built on Ubuntu , running on Ubuntu 16.04 (32 bits)

**Comment by jagenjo** [comment]
you were right, I just uploaded a version fixing the bug of setValue.

about the popup, you must include the CSS litegraph.css in your website too
