### ISSUE TITLE
Should use same order for serialized `LLink` array

### ISSUE THREAD

**Issue by NateScarlet** [jagenjo/litegraph.js#74]
https://github.com/jagenjo/litegraph.js/blob/c6b16f04e0c2859d0b9dfe07104a594713305912/src/litegraph.js#L1637-L1644

https://github.com/jagenjo/litegraph.js/blob/c6b16f04e0c2859d0b9dfe07104a594713305912/src/litegraph.js#L1479-L1486

And `LLink.serialize` never used?

**Comment by jagenjo** [comment]
ups, I created the LLink class some months ago and forgot to call serialize, before I was just creating a regular object.

I will fix it now, thanks for pointing it out

**Comment by jagenjo** [comment]
done
