### ISSUE TITLE
Read only mode

### ISSUE THREAD

**Issue by calvaradocl** [jagenjo/litegraph.js#80]
Hi there,

Is there a way or a method where I can work out a read-only mode for the graph?

**Comment by jagenjo** [comment]
describe read-only

**Comment by calvaradocl** [comment]
A mode where the graph can only be viewed (zoom, pan), but without being able to edit links, nodes (restrict even movement), only for showing the graph and it's connections for a view-only scenario.

**Comment by jagenjo** [comment]
done
```js
 graphcanvas.read_only = true;
```

**Comment by calvaradocl** [comment]
Great, thanks you @jagenjo
