### ISSUE TITLE
Context menu doesn't work in full screen (demo)

### ISSUE THREAD

**Issue by johndark** [jagenjo/litegraph.js#81]
Hi,

Firefox v66.0.5. If you press the full-screen icon at the top-right corner and then right mouse button you won't see the context menu. But if you hit F11 and enter into the full-window mode, it will work well.

**Comment by jagenjo** [comment]
I see, I guess the context menu element is occluded behind, I will see if there is any solution to that.

**Comment by jagenjo** [comment]
solved
