### ISSUE TITLE
[ES] A simple loop behaviour

### ISSUE THREAD

**Issue by CosasDePuma** [jagenjo/litegraph.js#82]
Ya que he visto que eres de Barcelona, así que me voy a tomar la licencia de relatarte el problema que he hayado en castellano. **(If you prefer that I speak in English, just tell me.)**

> Lo primero de todo, soy fan de esta librería. Mil veces mejor que la conocida Rete.js en todo lo relacionado con la interfaz gráfica, además de que es sencilla de programar y modificar.

El caso es que quiero hacer un [lenguaje de programación basado en nodos](https://github.com/CosasDePuma/Alfred/tree/visual/) y necesito imitar el comportamiento de los bucles _for_, _while_, _do-while_, etc.

He intentado codificarlo usando tu [demo de LiteGraph](http://tamats.com/projects/litegraph/demo/) y el resultado no ha sido el esperado:

![issues](https://user-images.githubusercontent.com/26680023/60552873-f4a5ac00-9d30-11e9-965f-66978e3ce9a6.png)

Como puedes ver, el contador se para en 8 cuando debería detenerse en 7. Aún no he encontrado el motivo por el cual esto ocurre así.

Para no tener que andar a colocar nodos y replicar mi programa, puedes cargarlo desde la consola:

```js
graph.configure(JSON.parse("{\"last_node_id\":19,\"last_link_id\":29,\"nodes\":[{\"id\":10,\"type\":\"events/trigger\",\"pos\":[512,340],\"size\":{\"0\":140,\"1\":46},\"flags\":{},\"mode\":0,\"inputs\":[{\"name\":\"in\",\"type\":0,\"link\":25}],\"outputs\":[{\"name\":\"true\",\"type\":-1,\"links\":[13]},{\"name\":\"change\",\"type\":-1,\"links\":null}],\"properties\":{}},{\"id\":15,\"type\":\"events/trigger\",\"pos\":[840,50],\"size\":{\"0\":140,\"1\":46},\"flags\":{},\"mode\":0,\"inputs\":[{\"name\":\"in\",\"type\":0,\"link\":26}],\"outputs\":[{\"name\":\"true\",\"type\":-1,\"links\":[12]},{\"name\":\"change\",\"type\":-1,\"links\":null}],\"properties\":{}},{\"id\":19,\"type\":\"widget/button\",\"pos\":[285,297],\"size\":[164,84],\"flags\":{},\"mode\":0,\"outputs\":[{\"name\":\"\",\"type\":-1,\"links\":[27]},{\"name\":\"\",\"type\":\"boolean\",\"links\":null}],\"properties\":{\"text\":\"Reset\",\"font_size\":30,\"message\":\"\"}},{\"id\":2,\"type\":\"widget/button\",\"pos\":[103,297],\"size\":[164,84],\"flags\":{},\"mode\":0,\"outputs\":[{\"name\":\"\",\"type\":-1,\"links\":[4]},{\"name\":\"\",\"type\":\"boolean\",\"links\":null}],\"properties\":{\"text\":\"Start\",\"font_size\":30,\"message\":\"\"}},{\"id\":1,\"type\":\"events/sequencer\",\"pos\":[329,105],\"size\":{\"0\":140,\"1\":126},\"flags\":{\"horizontal\":true,\"render_box\":false,\"collapsed\":false},\"mode\":0,\"inputs\":[{\"name\":\"\",\"type\":-1,\"link\":4},{\"name\":\"\",\"type\":-1,\"link\":13},{\"name\":\"\",\"type\":-1,\"link\":null},{\"name\":\"\",\"type\":-1,\"link\":null},{\"name\":\"\",\"type\":-1,\"link\":null},{\"name\":\"\",\"type\":-1,\"link\":null}],\"outputs\":[{\"name\":\"\",\"type\":-1,\"links\":[]},{\"name\":\"\",\"type\":-1,\"links\":[28]},{\"name\":\"\",\"type\":-1,\"links\":null},{\"name\":\"\",\"type\":-1,\"links\":null},{\"name\":\"\",\"type\":-1,\"links\":null},{\"name\":\"\",\"type\":-1,\"links\":null}],\"properties\":{}},{\"id\":5,\"type\":\"events/counter\",\"pos\":[510,38],\"size\":{\"0\":140,\"1\":66},\"flags\":{},\"mode\":0,\"inputs\":[{\"name\":\"inc\",\"type\":-1,\"link\":28},{\"name\":\"dec\",\"type\":-1,\"link\":null},{\"name\":\"reset\",\"type\":-1,\"link\":27}],\"outputs\":[{\"name\":\"change\",\"type\":-1,\"links\":null},{\"name\":\"num\",\"type\":\"number\",\"links\":[19,23]}],\"properties\":{}},{\"id\":7,\"type\":\"widget/number\",\"pos\":[533,165],\"size\":[80,60],\"flags\":{\"collapsed\":false},\"mode\":0,\"outputs\":[{\"name\":\"\",\"type\":\"number\",\"links\":[20,24]}],\"properties\":{\"min\":-1000,\"max\":1000,\"value\":6,\"step\":1}},{\"id\":18,\"type\":\"math/condition\",\"pos\":[731,168],\"size\":[80,60],\"flags\":{\"collapsed\":false},\"mode\":0,\"inputs\":[{\"name\":\"A\",\"type\":\"number\",\"link\":23},{\"name\":\"B\",\"type\":\"number\",\"link\":24}],\"outputs\":[{\"name\":\"out\",\"type\":\"boolean\",\"links\":[25]}],\"properties\":{\"A\":8,\"B\":6,\"OP\":\"<=\"}},{\"id\":17,\"type\":\"math/condition\",\"pos\":[729,53],\"size\":[80,60],\"flags\":{\"collapsed\":false},\"mode\":0,\"inputs\":[{\"name\":\"A\",\"type\":\"number\",\"link\":19},{\"name\":\"B\",\"type\":\"number\",\"link\":20}],\"outputs\":[{\"name\":\"out\",\"type\":\"boolean\",\"links\":[26]}],\"properties\":{\"A\":8,\"B\":6,\"OP\":\">\"}},{\"id\":9,\"type\":\"basic/watch\",\"pos\":[1056,50],\"size\":{\"0\":140,\"1\":26},\"flags\":{},\"mode\":0,\"inputs\":[{\"name\":\"value\",\"type\":0,\"link\":12,\"label\":\"null\"}],\"properties\":{}}],\"links\":[[4,2,0,1,0,-1],[12,15,0,9,0,0],[13,10,0,1,1,-1],[19,5,1,17,0,\"number\"],[20,7,0,17,1,\"number\"],[23,5,1,18,0,\"number\"],[24,7,0,18,1,\"number\"],[25,18,0,10,0,0],[26,17,0,15,0,0],[27,19,0,5,2,-1],[28,1,1,5,0,-1]],\"groups\":[],\"config\":{},\"version\":0.4}"));
```

Muchísimas gracias de antemano por todo, :rocket:

**Comment by jagenjo** [comment]
Wenas Kike:

Me alegra de que te guste LiteGraph, le he metido muchas horas.

La idea de usar litegraph como lenguaje de programacion hace tiempo que me ronda por la cabeza, el problema es que no fue diseñada con esa finalidad en mente, sino mas para gestionar flujos de datos. De hecho la opcion de lanzar eventos la añadi mucho mas tarde para explorar comportamientos mas orientados a logica.

El problema es que con la actual arquitectura cuesta crear ciertas logicas que por codigo son muy simples y acabo haciendo parches que no me gusta.

En tu ejemplo (que me ha sorprendido porque no pensé que fuese posible hacer un loop con los nodos que vienen ahora) el problema es por la arquitectura del sistema, los eventos y los datos no viajan a la vez, eso significa que un evento puede incrementar un valor pero el siguiente nodo evalua el dato anterior, de ahi ese offset. Solucionarlo no es facil y llevo tiempo dandole vueltas al problema pero volveré a mirar.

La solucion mas rapida pasa por hacer una caja Loop, quiza me anime y la programe pero creo que seria un poco engañosa ya que daria a entender que litegraph permite programar y no es su finalidad.

Ya me contaras tus avances, enviame mails a mi mail personal javi.agenjo@gmail.com

Un saludo

**Comment by CosasDePuma** [comment]
Muchisimas gracias por contestar tan rápido y tan detalladamente.

Ya me fijé que LiteGraph está enfocado a flujos de datos constantes y no a algo más parecido a la programación, ¿pero de eso se trata lo que quiero hacer, no?
Así que modificaré LiteGraph para que se adapte a lo que necesito, como llevo haciendo estos dias, y a ver si consigo lo de los bucles sin crear una chapuza de código 😓

Una vez funcione todo mas o menos bien, te mandaré un correo para que veas el resultado y opines.

Además referenciaré este repositorio desde mi proyecto porque como ya dije, es brutal.

Doy por cerrado el Issue, un salido ^^
