### ISSUE TITLE
trying to add a new node

### ISSUE THREAD

**Issue by RiccardoRossi** [jagenjo/litegraph.js#84]
hello,
         i'd like to tell upfront that i have no expertise with node.js, so 99.99% my problems come out of this.

i tried to add a new file riccardo.js in the same directory as math.js

the content of that file is

~~~js
(function(global) {
    var LiteGraph = global.LiteGraph;
    
    //******************************************************************* */
    function FirstTest() {
        this.addInput("in", "number");
        this.addOutput("out", "number");
        this.size = [80, 30];
    }

    FirstTest.title = "FirstTest";
    FirstTest.desc = "trying to add a new node";

    FirstTest.prototype.onExecute = function() {
        var v = this.getInputData(0);
        if (v == null) {
            return;
        }
        this.setOutputData(0, 5000.0);
    };

    LiteGraph.registerNodeType("riccardo/FirstTest", FirstTest);
}ricc //glMatrix
)(this);
~~~

unfortunately when i try to add a node i cannot see that in the list.

i did also add the riccardo.js in the gruntfile.js, and reinstalled the stuff before reopening it...but so far with no luck...

can u see anything obviously wrong?

btw, if yo

**Comment by jagenjo** [comment]
I never used grunt or anything like that, so try this:

```js
var LiteGraph = global.LiteGraph;
    
    //******************************************************************* */
    function FirstTest() {
        this.addInput("in", "number");
        this.addOutput("out", "number");
        this.size = [80, 30];
    }

    FirstTest.title = "FirstTest";
    FirstTest.desc = "trying to add a new node";

    FirstTest.prototype.onExecute = function() {
        var v = this.getInputData(0);
        if (v == null) {
            return;
        }
        this.setOutputData(0, 5000.0);
    };

    LiteGraph.registerNodeType("riccardo/FirstTest", FirstTest);

  console.log("riccardo node created"); //helps to debug
```

now be sure that file is included, it should work

**Comment by RiccardoRossi** [comment]
i think that your last sentence is crucial...

where should i include it?

**Comment by jagenjo** [comment]
which sentence?

It depends on your build system, I dont use any of it, just include that JS from my HTML.

**Comment by jagenjo** [comment]
wait, there was an error in the first line on the code I pasted in my other comment, just fixed it.

**Comment by RiccardoRossi** [comment]
mmm ... this is getting me a confirmation that i don't understand anything of javascript.

i just added the "riccardo.js" in the same directory as "math.js" 

then i did

~~~
rrossi@Latitude-E5450:~/scratch/litegraph/litegraph.js-master$ sudo npm install
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

audited 3793 packages in 2.47s
found 0 vulnerabilities

rrossi@Latitude-E5450:~/scratch/litegraph/litegraph.js-master$ sudo node utils/server.js 
Example app listening on port 80!

~~~

i thought that "npm install" would build the lightgraph stuff. 

the problem is that as shown in the next snapshot there is no trace of riccardo when i try to add a node

![Screenshot from 2019-10-12 16-30-40](https://user-images.githubusercontent.com/8059665/66702971-b2b3db00-ed0d-11e9-9133-205b0ac58f55.png)

**Comment by RiccardoRossi** [comment]
ok, found the mistery, i needed to add to "index.html"

really sorry for wasting your time
