### ISSUE TITLE
Disable double click on canvas?

### ISSUE THREAD

**Issue by damntourists** [jagenjo/litegraph.js#86]
I'm not finding any information regarding removing the default double-click functionality in empty areas on the node graph. Is it possible? I'd like to remove access to the search bar.

**Comment by jagenjo** [comment]
graphcanvas.allow_searchbox = false;

**Comment by damntourists** [comment]
Perhaps I'm doing this wrong... I've tried setting:
```
  componentDidMount() {
    const graph = new LiteGraph.LGraph();
    const canvas = new LiteGraph.LGraphCanvas("#node-graph", graph);

    canvas.allow_interaction = false;           // <--- works, nodes can't be interacted with
    canvas.allow_dragcanvas = false;         // <--- works, canvas will not pan
    canvas.allow_searchbox = false;           // <--- does not work, double click still opens search bar at bottom.
```

```

**Comment by jagenjo** [comment]
sorry, you were right, there was a bug, I just fixed it and upload it.

**Comment by damntourists** [comment]
Oh awesome, thanks!

**Comment by damntourists** [comment]
Was this tagged as version 0.7.0? I just updated, removed and reinstalled and not seeing the fix. Double-clicking on an empty part of the canvas still pops up a search bar at the bottom.

**Comment by jagenjo** [comment]
you are using npm I guess, the problem is that I do not keep the npm package updated, another user was doing that. I just keep the repo update. Can you just download litegraph.js from the repo and replace the one you have?

**Comment by damntourists** [comment]
It's probably worth pulling it from npm if you don't plan on keeping that updated. The project I'm working on has an automated build through docker which then gets deployed to a cluster. Adding in a one-off hack to install a non-npm supported package isn't ideal.
