### ISSUE TITLE
Investigate if toposort could be useful for auto position of nodes

### ISSUE THREAD

**Issue by kriffe** [jagenjo/litegraph.js#9]
Perhaps the toposort library could be used for automatic node placement (if not already implemented)?

Or perhaps it could be useful in some other way.

https://www.npmjs.com/package/toposort

Used in https://github.com/GooTechnologies/shader-graph

**Comment by jagenjo** [comment]
I can implement it easily, I already have the level where every node belongs. I will try

**Comment by kriffe** [comment]
Great!

Looks like the package is designed to be a node module (used with require). If you rewrite the last lines in topsort.js as an optional export (see below) it can be tested. And if it works good I can publish a fork on npm with the optional and we can include it as a dependency in through npm (npm install package.json --save topsort)

Original end of file
```js
//... 
module.exports = topsort
```

Rewrite for include as <script src='topsort.js'>
```js
//... 
if (typeof module !== 'undefined' && typeof module.exports !== 'undefined'){
    module.exports = topsort
}
```

**Comment by Powback** [comment]
Has there been any work on this? I've got some fairly large and complex node graphs that could use some sorting.
![image](https://user-images.githubusercontent.com/970246/37836028-caa62054-2eb1-11e8-8812-670460fa71e2.png)

**Comment by jagenjo** [comment]
I will consider programing my own sorting function to limit dependencies, but besides that, how the heck did you manage to create that!

**Comment by Powback** [comment]
Great! 

The graph is from Battlefield 3 data. It's basically how the game handles everything about an object, kinda like Unreal's Blueprint system.

Here it is if you want to check it out.
http://powback.com/wEBX/#Characters/Soldiers/MpSoldier.json

**Comment by kriffe** [comment]
@jagenjo : Have you considered adding a wrapper to the compiler (or in the future perhaps use webpack)? This should ensure that the library has no dependencies when used externally. Functions like topsort will then be bundled inside the closure and the use wont notice or be able to interact.

Probably need of exporting multiple functions (LGraph, LGraphCanvas, LGraphNode) or bundling into a LITEGRAPH container as discussed in https://github.com/jagenjo/litegraph.js/issues/12

Compiler arg for google-closure-compiler (in grunt-script)
```
output_wrapper: '"var LITEGRAPH = (function(){%output% return LITEGRAPH;}).call(this);"'
```

**Comment by jagenjo** [comment]
Well, Im still very hesitant to add dependencies to my libraries, because they make the litegraph base library grow exponentially, but I understand your point of view.

Currently LiteGraph can run on nodejs (I added that last month) so it shouldnt be a problem to create another repo that includes more features without having to include it in the core library.

**Comment by kriffe** [comment]
@jagenjo Ah, nice! i see that now. Then a closure is already in place.

Could perhaps a repo called litegrpah-editor.js be created and have theese kind of functions like topsort? If possible from local example or from the webglstudio.js project perhaps?

**Comment by Powback** [comment]
I have implemented a positioning system using [Springly](https://github.com/dhotson/springy), and the results are pretty good with just 3 lines of code. 

![image](https://user-images.githubusercontent.com/970246/37904155-1e9c5a7a-30fb-11e8-9a23-12e6b4a9299d.png)

I'm still looking into some solutions that are less physics-based.

**Comment by Powback** [comment]
For future reference: I had great success with [Cytoscape](https://github.com/cytoscape/cytoscape.js) as a translation layer:
![image](https://user-images.githubusercontent.com/970246/37950636-9c3d063e-3199-11e8-8fb3-ea1065a67164.png)

I simply generated the Cytoscape graph simultaneously and applied the generated node positions to the Litegraph nodes as well.

**Comment by jagenjo** [comment]
well, that approach looks way better than mine.

I just uploaded a new method for LGraph called arrange, this method sorts the nodes according to level of dependencies, it doesnt look perfect but good enough for most cases. I will give it another try in the future to get something closer to what you got.

**Comment by phineas-pta** [comment]
@Powback if possible can u share code example of using cytoscape with litegraph ? thanks

**Comment by Powback** [comment]
> @Powback if possible can u share code example of using cytoscape with litegraph ? thanks

Yeah, you can find some reference code here: https://github.com/Powback/wEBX/blob/master/script/NodeGraph.js#L1095

**Comment by phineas-pta** [comment]
ty for the fast answer 😄

**Comment by phineas-pta** [comment]
@Powback just fyi in fact u dont have to import `cytoscape.js` nor `cytoscape-dagre.js` at all, only need `dagre.js` coz that's what actually arrange nodes not cytoscape

u can check out my quick dirty code: comfyanonymous/ComfyUI#1547
