### ISSUE TITLE
Extremely low FPS on firefox when zoomed out

### ISSUE THREAD

**Issue by brockelmore** [jagenjo/litegraph.js#92]
I get less than 1 FPS when I am zoomed out (with only 20 nodes) on Firefox. On chrome, I get a steady 60 FPS.

Any thoughts as to how I could fix this?

**Comment by jagenjo** [comment]
I cannot reproduce, trying with the latest firefox version and with 100 nodes on the screen I get around 20 fps. Which version of firefox do you use?

**Comment by jagenjo** [comment]
I just uploaded a version disabling the shadows when rendering from far away, I get better framerate now. Let me know if it works better for you.

**Comment by brockelmore** [comment]
I’m v70 on MacOS Mojave. Probably some obscure thing to do with Firefox

**Comment by brockelmore** [comment]
Wow you crushed it. Nice work
