### ISSUE TITLE
Demo link redirects to non-Demo page

### ISSUE THREAD

**Issue by dirkk0** [jagenjo/litegraph.js#94]
Cheers,  Dirk

**Comment by jagenjo** [comment]
It is strange because it doesnt happen to me. Maybe is related to some browser using IP6 instead of IP4, I will investigate.

**Comment by jagenjo** [comment]
Can you check if it happens now?

**Comment by dirkk0** [comment]
Yes, it works!
And it looks great!
Thanks for open sourcing this.
Closing this now.

**Comment by jagenjo** [comment]
Thanks for the issue, I still have problems configuring my http server in IP6+SSL
