### ISSUE TITLE
engine flow documentation

### ISSUE THREAD

**Issue by joshmarinacci** [jagenjo/litegraph.js#96]
The docs should describe the mental model of the engine's workflow.  For example, should data be updated on every tick (the execute method) or when configuration changes (add nodes, change connections, etc).  How should one node obtain the data from the thing attached to it?  When does data flow? Is it on demand when one node requests it from it's inputs or is it pushed in a right to left sweep?  This information is needed so that the developer can figure out how to map the UI onto their underlying data model.

**Comment by jagenjo** [comment]
Ok, I will write some paragraphs about it, but the flow is very simple:
The system calls onExecute on every node, then nodes do whatever they want inside. The execution order is determined by the graph morphology (nodes with only outputs are executed first, etc).

When rendering they are executed according to the order in the graph._nodes array, which is usually the last clicked ones are in the last positions of the array.

Not much else to say. On top of that you build whatever you want, if you want to precompute stuff, store it per node, is up to you, there are callbacks for almost everything.
