### ISSUE TITLE
Wrong style at the demo page

### ISSUE THREAD

**Issue by cwxyz007** [jagenjo/litegraph.js#97]
Chrome: Version 79.0.3945.117 (Official Build) (64-bit)
Window 10

Reproduce:
1. open `https://tamats.com/projects/litegraph/demo/`
2. select `Audio Delay` or `Audio Reverb`

![image](https://user-images.githubusercontent.com/14226737/72042356-46834c00-32e9-11ea-835f-7e0753f241dd.png)
![image](https://user-images.githubusercontent.com/14226737/72042375-5733c200-32e9-11ea-8f8c-679723053132.png)

**Comment by jagenjo** [comment]
Fixed, this was caused because I changed the default title size and old JSONs still had the old size.
